import type { SpellDef } from "../spells.js";

export const SPELLS_L0: Record<string, SpellDef> = {
  "Acid Splash": {
    name: "Acid Splash",
    namePl: "Prysk kwasu",
    level: 0,
    school: "Conjuration",
    components: "V, S",
    description:
      "Rzucasz bańkę kwasu na jeden cel w zasięgu 60 stóp (lub dwa cele w odległości 5 stóp od siebie). Każdy cel wykonuje rzut obronny na Zręczność; nieudany rzut oznacza 1k6 obrażeń kwasowych.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "acid",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Blade Ward": {
    name: "Blade Ward",
    namePl: "Ochrona ostrzy",
    level: 0,
    school: "Abjuration",
    components: "V, S",
    description:
      "Rysujesz w powietrzu znak ochronny; do początku twojej następnej tury masz odporność na obrażenia obuchowe, tnące i kłute. Zaklęcie wymaga akcji, więc najlepiej rzucić je z wyprzedzeniem.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 round",
      castingTime: "action",
    },
  },
  "Booming Blade": {
    name: "Booming Blade",
    namePl: "Grzmiące ostrze",
    level: 0,
    school: "Evocation",
    components: "S, M",
    description:
      "Wykonujesz atak bronią w zwarciu; przy trafieniu cel zostaje owinięty grzmiącą energią do początku twojej następnej tury. Jeśli cel dobrowolnie przemieści się o 5 stóp lub więcej, otrzymuje 1k8 obrażeń grzmotowych.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "thunder",
      attack: true,
      range: "Self (5 ft)",
      duration: "1 round",
      castingTime: "action",
    },
  },
  "Chill Touch": {
    name: "Chill Touch",
    namePl: "Zimny dotyk",
    level: 0,
    school: "Necromancy",
    components: "V, S",
    description:
      "Wysyłasz widmową, kostniejącą dłoń do celu w zasięgu 120 stóp. Wykonaj rzut ataku; trafienie zadaje 1k8 obrażeń nekrotycznych, a cel nie może odzyskiwać punktów życia do początku twojej następnej tury.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "necrotic",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Control Flames": {
    name: "Control Flames",
    namePl: "Kontrola ognia",
    level: 0,
    school: "Transmutation",
    components: "S",
    description:
      "Wskazujesz niemagiczny płomień mieszczący się w kostce 5 stóp w zasięgu 60 stóp i manipulujesz nim: możesz go rozszerzyć, zgasić, zmienić barwę albo natężenie światła. Dzięki tej sztuczce możesz też uformować proste kształty wewnątrz płomienia.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Create Bonfire": {
    name: "Create Bonfire",
    namePl: "Ognisko",
    level: 0,
    school: "Conjuration",
    components: "V, S",
    description:
      "Na ziemi w zasięgu 60 stóp rozniecasz ognisko wypełniające sześcian o boku 5 stóp. Istota w tym miejscu wykonuje rzut obronny na Zręczność; nieudany rzut oznacza 1k8 obrażeń ogniowych (rzut powtarza się przy wejściu w płomienie lub zakończeniu w nich tury).",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Dancing Lights": {
    name: "Dancing Lights",
    namePl: "Tańczące światła",
    level: 0,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz do czterech świateł w zasięgu 120 stóp, z których każde świeci jasnym światłem w promieniu 10 stóp i może się dowolnie przemieszczać. Światła gasną, gdy zaklęcie się kończy lub oddalisz się od nich o ponad 120 stóp.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Druidcraft": {
    name: "Druidcraft",
    namePl: "Sztuka druidy",
    level: 0,
    school: "Transmutation",
    components: "V, S",
    description:
      "Przywołujesz drobny przejaw natury: kiełkujący kwiat, brzęczenie owadów, zapowiedź pogody albo nieśmiały podmuch wiatru. Efekt jest czysto narracyjny — DM rozstrzyga szczegóły sceny.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Eldritch Blast": {
    name: "Eldritch Blast",
    namePl: "Mistyczny pocisk",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Ze swojej dłoni wystrzeliwujesz smugi energii uderzające w cel w zasięgu 120 stóp. Wykonaj rzut ataku; trafienie zadaje 1k10 obrażeń siłowych (na wyższych poziomach liczba smug rośnie).",
    effect: {
      kind: "damage",
      dice: "1d10",
      damageType: "force",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Elementalism": {
    name: "Elementalism",
    namePl: "Elementalizm",
    level: 0,
    school: "Transmutation",
    components: "V, S",
    description:
      "Manipulujesz otoczeniem elementarnymi siłami: rozniecasz płomień, osuszasz błoto, rozpraszasz mgłę albo tworzysz niegroźne efekty sensoryczne. Zaklęcie ma zastosowania czysto narracyjne i nie zadaje obrażeń.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Fire Bolt": {
    name: "Fire Bolt",
    namePl: "Pocisk ognia",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Wystrzeliwujesz pocisk ognia w cel w zasięgu 120 stóp. Wykonaj rzut ataku; trafienie zadaje 1k10 obrażeń ogniowych i może podpalić łatwopalne przedmioty, których nie nosi żadna istota.",
    effect: {
      kind: "damage",
      dice: "1d10",
      damageType: "fire",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Friends": {
    name: "Friends",
    namePl: "Przyjaciele",
    level: 0,
    school: "Enchantment",
    components: "S, M",
    description:
      "Czarujesz jedną istotę, która nie jest wobec ciebie wroga: masz przewagę w testach Charyzmy skierowanych do niej. Po upływie zaklęcia istota wie, że była zmanipulowana, i może stać się wroga.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Frostbite": {
    name: "Frostbite",
    namePl: "Odmrożenie",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Ścinasz mrozem skórę celu w zasięgu 60 stóp. Cel wykonuje rzut obronny na Kondycję; nieudany rzut oznacza 1k6 obrażeń zimnych, a cel ma niekorzystną pozycję w następnym rzucie ataku.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "cold",
      attack: false,
      save: "constitution",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Green-Flame Blade": {
    name: "Green-Flame Blade",
    namePl: "Ostrze zielonego ognia",
    level: 0,
    school: "Evocation",
    components: "S, M",
    description:
      "Wykonujesz atak bronią w zwarciu; przy trafieniu cel otrzymuje normalne obrażenia broni, a zielony ogień przeskakuje na inną istotę w promieniu 5 stóp. Ta druga istota otrzymuje 1k8 obrażeń ogniowych.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "fire",
      attack: true,
      range: "Self (5 ft)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Guidance": {
    name: "Guidance",
    namePl: "Wskazówka",
    level: 0,
    school: "Divination",
    components: "V, S",
    description:
      "Dotykasz zgodnej istoty i udzielasz jej boskiej wskazówki: raz w ciągu następnej minuty może dodać 1k4 do testu umiejętności. Zaklęcie wymaga koncentracji i kończy się po wykorzystaniu kości.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Gust": {
    name: "Gust",
    namePl: "Podmuch",
    level: 0,
    school: "Transmutation",
    components: "V, S",
    description:
      "Przywołujesz podmuch wiatru, który może przesunąć małą istotę o 5 stóp (rzut obronny na Siłę) albo odepchnąć drobny przedmiot. Zaklęcie nie zadaje obrażeń, ale pomaga w interakcjach ze sceną.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Magic Stone": {
    name: "Magic Stone",
    namePl: "Magiczny kamień",
    level: 0,
    school: "Transmutation",
    components: "V, S",
    description:
      "Akcją dodatkową dotykasz do trzech kamyków, które przez minutę stają się magiczną bronią o zasięgu 60 stóp. Rzut ataku przy ich użyciu wykonuje się modyfikatorem zdolności rzucania zaklęć; trafienie zadaje 1k6 + modyfikator obrażeń obuchowych.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "bludgeoning",
      attack: true,
      range: "Touch",
      duration: "1 min",
      castingTime: "bonus",
    },
  },
  "Mending": {
    name: "Mending",
    namePl: "Naprawa",
    level: 0,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotykasz przedmiotu i naprawiasz pojedyncze pęknięcie lub rozdarcie o długości do 1 stopy. Zaklęcie nie działa na magiczne przedmioty i nie odtwarza zupełnie zniszczonych części.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Message": {
    name: "Message",
    namePl: "Wiadomość",
    level: 0,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Szepczesz wiadomość do istoty w zasięgu 120 stóp; słyszy ją tylko ona i może odpowiedzieć szeptem, który ty usłyszysz. Przez otwarte przestrzenie dźwięk dociera bez przeszkód, ale kamień lub cienkie drewno go zagłusza.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Mind Sliver": {
    name: "Mind Sliver",
    namePl: "Odłamek myśli",
    level: 0,
    school: "Enchantment",
    components: "V",
    description:
      "Przesyłasz psychiczną igłę w umysł celu w zasięgu 60 stóp. Cel wykonuje rzut obronny na Inteligencję; nieudany rzut oznacza 1k6 obrażeń psychicznych, a cel odejmuje 1k4 od następnego rzutu obronnego przed końcem swojej następnej tury.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "psychic",
      attack: false,
      save: "intelligence",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Minor Illusion": {
    name: "Minor Illusion",
    namePl: "Drobna iluzja",
    level: 0,
    school: "Illusion",
    components: "S, M",
    description:
      "Tworzysz dźwięk lub nieruchomy obraz w zasięgu 30 stóp — na przykład głos, tupot kroków albo skrzynię. Istota, która zbada iluzję, może ją zdemaskować, wykonując akcję i test Inteligencji (Badanie).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Mold Earth": {
    name: "Mold Earth",
    namePl: "Formowanie ziemi",
    level: 0,
    school: "Transmutation",
    components: "S",
    description:
      "Manipulujesz luźną ziemią w kostce 5 stóp w zasięgu 30 stóp: możesz wykopać dół, usypać kopiec, spłaszczyć grunt albo zamienić teren w trudny. Efekt utrzymuje się do czasu, aż ktoś ponownie ukształtuje to miejsce.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Poison Spray": {
    name: "Poison Spray",
    namePl: "Prysk trucizny",
    level: 0,
    school: "Conjuration",
    components: "V, S",
    description:
      "Z twojej dłoni tryska chmura zielonej trucizny w stronę celu w zasięgu 30 stóp. Wykonaj rzut ataku; trafienie zadaje 1k12 obrażeń truciznowych.",
    effect: {
      kind: "damage",
      dice: "1d12",
      damageType: "poison",
      attack: true,
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Prestidigitation": {
    name: "Prestidigitation",
    namePl: "Prestydygitacja",
    level: 0,
    school: "Transmutation",
    components: "V, S",
    description:
      "Rzucasz drobną magię, która upraszcza życie: czyścisz lub brudzisz przedmiot, podsycasz ogień, schładzasz napój albo tworzysz niegroźny efekt sensoryczny trwający do godziny. Zaklęcie nie zadaje obrażeń ani nie wpływa na mechanikę walki.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Produce Flame": {
    name: "Produce Flame",
    namePl: "Wytworzenie ognia",
    level: 0,
    school: "Conjuration",
    components: "V, S",
    description:
      "W twojej dłoni przez 10 minut płonie nieszkodliwy dla ciebie płomień, który oświetla otoczenie i pozwala podpalać przedmioty. Możesz rzucić go w cel: wykonaj rzut ataku; trafienie zadaje 1k8 obrażeń ogniowych.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "fire",
      attack: true,
      range: "Self",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Ray of Frost": {
    name: "Ray of Frost",
    namePl: "Promień mrozu",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Z twojego palca wystrzeliwuje lodowaty promień w cel w zasięgu 60 stóp. Wykonaj rzut ataku; trafienie zadaje 1k8 obrażeń zimnych i zmniejsza prędkość celu o 10 stóp do początku twojej następnej tury.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "cold",
      attack: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Resistance": {
    name: "Resistance",
    namePl: "Odporność",
    level: 0,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotykasz istoty, która raz w ciągu następnej minuty może dodać 1k4 do rzutu obronnego. Zaklęcie wymaga koncentracji i znika po wykorzystaniu kości lub upływie czasu.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Shillelagh": {
    name: "Shillelagh",
    namePl: "Shillelagh",
    level: 0,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Akcją dodatkową otaczasz magiczną energią buławę lub kostur, który przez minutę staje się bronią magiczną. Przy ataku używa się modyfikatora zdolności rzucania zaklęć, a obrażenia wynoszą 1k8 (rozstrzygane narracyjnie przez DM).",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "bonus",
    },
  },
  "Shocking Grasp": {
    name: "Shocking Grasp",
    namePl: "Piorunujący chwyt",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Błyskawica przeskakuje z twojej ręki na dotkniętą istotę. Wykonaj rzut ataku w zwarciu; trafienie zadaje 1k8 obrażeń błyskawic, a cel traci reakcje do początku swojej następnej tury (atak przeciw celowi w metalowym pancerzu wykonuje się z przewagą).",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "lightning",
      attack: true,
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Sorcerous Burst": {
    name: "Sorcerous Burst",
    namePl: "Magiczny wybuch",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Wysyłasz w cel w zasięgu 120 stóp skwierczącą kulę czystej magii, której rodzaj obrażeń wybierasz przy rzuceniu (kwas, zimno, ogień, siłowe, błyskawice, trucizna, psychiczne lub grzmot). Wykonaj rzut ataku; trafienie zadaje 1k8 obrażeń (uproszczenie: pojedynczy rzut zamiast przerzucania ósemek).",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "force",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Starry Wisp": {
    name: "Starry Wisp",
    namePl: "Gwiezdny płomyk",
    level: 0,
    school: "Evocation",
    components: "V, S",
    description:
      "Z twojej dłoni wystrzeliwuje świetlisty płomyk w cel w zasięgu 60 stóp, otaczając go przyćmionym światłem. Wykonaj rzut ataku; trafienie zadaje 1k8 obrażeń promienistych.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "radiant",
      attack: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Thorn Whip": {
    name: "Thorn Whip",
    namePl: "Bicz z cierni",
    level: 0,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przywołujesz bicz z cierni, który smaga cel w zasięgu 30 stóp. Wykonaj rzut ataku; trafienie zadaje 1k6 obrażeń kłutych i przyciąga cel o 10 stóp w twoją stronę.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "piercing",
      attack: true,
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Thunderclap": {
    name: "Thunderclap",
    namePl: "Grzmot",
    level: 0,
    school: "Evocation",
    components: "S",
    description:
      "Wywołujesz ogłuszający grzmot, który ogarnia wszystkie istoty w promieniu 5 stóp od ciebie. Każda z nich wykonuje rzut obronny na Kondycję; nieudany rzut oznacza 1k6 obrażeń grzmotowych.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "thunder",
      attack: false,
      save: "constitution",
      range: "Self (5 ft)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Toll the Dead": {
    name: "Toll the Dead",
    namePl: "Pogrzebowy dzwon",
    level: 0,
    school: "Necromancy",
    components: "V, S",
    description:
      "Duchowy dzwon rozdzwania się wokół celu w zasięgu 60 stóp. Cel wykonuje rzut obronny na Mądrość; nieudany rzut oznacza 1k8 obrażeń nekrotycznych (1k12, jeśli celowi brakuje punktów życia).",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "necrotic",
      attack: false,
      save: "wisdom",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "True Strike": {
    name: "True Strike",
    namePl: "Prawdziwy cios",
    level: 0,
    school: "Divination",
    components: "S, M",
    description:
      "Akcją dodatkową skupiasz wolę na broni i wykonujesz atak, używając modyfikatora zdolności rzucania zaklęć do rzutu ataku i obrażeń. Koncentracja trwa do początku twojej następnej tury lub do wykonania ataku (uproszczenie: 1k8 obrażeń przy trafieniu).",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "force",
      attack: true,
      range: "Self",
      duration: "1 round",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Vicious Mockery": {
    name: "Vicious Mockery",
    namePl: "Złośliwa kpina",
    level: 0,
    school: "Enchantment",
    components: "V",
    description:
      "Wypowiadasz druzgocącą złośliwość pod adresem celu w zasięgu 60 stóp. Cel wykonuje rzut obronny na Mądrość; nieudany rzut oznacza 1k6 obrażeń psychicznych i niekorzystną pozycję w następnym rzucie ataku.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "psychic",
      attack: false,
      save: "wisdom",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Word of Radiance": {
    name: "Word of Radiance",
    namePl: "Słowo światłości",
    level: 0,
    school: "Evocation",
    components: "V, M",
    description:
      "Wypowiadasz święte słowo, a błysk światłości ogarnia każdą istotę w promieniu 5 stóp od ciebie. Każda z nich wykonuje rzut obronny na Kondycję; nieudany rzut oznacza 1k6 obrażeń promienistych.",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "radiant",
      attack: false,
      save: "constitution",
      range: "Self (5 ft)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
};
