import type { SpellDef } from "../spells.js";

export const SPELLS_L2: Record<string, SpellDef> = {
  "Acid Arrow": {
    name: "Acid Arrow",
    namePl: "Kwaśna strzała",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Wypuszczasz błyszczącą, zieloną strzałę, która trafia cel w zasięgu 90 stóp. Wykonaj rzut ataku zaklęciem; trafienie zadaje 4k4 obrażeń kwasowych, a kwas skwierczy na celu także na początku twojej następnej tury.",
    effect: {
      kind: "damage",
      dice: "4d4",
      damageType: "acid",
      attack: true,
      range: "90 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Aid": {
    name: "Aid",
    namePl: "Wsparcie",
    level: 2,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotykasz do trzech istot, wzmacniając ich wolę życia: ich maksymalna i bieżąca liczba punktów życia wzrasta o 5 na 8 godzin. Nie leczy ran, lecz dodaje wytrzymałości na cały dzień walki.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Alter Self": {
    name: "Alter Self",
    namePl: "Zmiana postaci",
    level: 2,
    school: "Transmutation",
    components: "V, S",
    description:
      "Kształtujesz własne ciało, wybierając jedną z form: nowy wygląd, naturalną broń zadającą 1k6 obrażeń lub umiejętność oddychania i pływania pod wodą. Efekt trwa do godziny, o ile utrzymujesz koncentrację — DM rozstrzyga zastosowania narracyjne.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Animal Messenger": {
    name: "Animal Messenger",
    namePl: "Zwierzęcy posłaniec",
    level: 2,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Drobne zwierzę w zasięgu 30 stóp przenosi krótką wiadomość do wybranego celu oddalonego o maksymalnie 50 mil. Zaklęcie można rzucić jako rytuał; posłaniec dociera do celu po kilku godzinach.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Arcane Lock": {
    name: "Arcane Lock",
    namePl: "Tajemny zamek",
    level: 2,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Zamykasz drzwi, skrzynię lub inny zamykany przedmiot na tajemny zamek: tylko ty wybierasz, kto może je otworzyć. Zaklęcie działa, dopóki nie zostanie rozproszone, a rzut obronny na siłę nie otworzy zamka.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Augury": {
    name: "Augury",
    namePl: "Wróżba",
    level: 2,
    school: "Divination",
    components: "V, S, M",
    description:
      "Rzucasz zaklęte patyczki, kości lub żetony, by poznać omen: czy wybrane działanie przyniesie dobro, zło, zarówno jedno i drugie, czy nie przyniesie nic. Wróżba dotyczy najbliższych 30 minut i nie bierze pod uwagę losowych okoliczności.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Barkskin": {
    name: "Barkskin",
    namePl: "Kora drzewa",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Skóra dotkniętej istoty staje się twarda i chropowata jak kora: jej Klasa Pancerza nie może być niższa niż 16. Efekt trwa godzinę, o ile utrzymujesz koncentrację — wspiera tankujących w pierwszej linii.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Beast Sense": {
    name: "Beast Sense",
    namePl: "Zmysły bestii",
    level: 2,
    school: "Divination",
    components: "S",
    description:
      "Dotykasz posłusznej bestii i przez godzinę widzisz i słyszysz jej zmysłami, nawet gdy oddali się na milę. Zaklęcie można rzucić jako rytuał — idealne do rozpoznania terenu przez zwierzęcego towarzysza.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Blur": {
    name: "Blur",
    namePl: "Rozmycie",
    level: 2,
    school: "Illusion",
    components: "V",
    description:
      "Twoje ciało staje się nieostre i rozmyte, przez co ataki wymierzone w ciebie są wykonywane z utrudnieniem. Efekt trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Branding Smite": {
    name: "Branding Smite",
    namePl: "Znaczące uderzenie",
    level: 2,
    school: "Evocation",
    components: "V",
    description:
      "Twoja broń rozbłyska świętym ogniem; następne uderzenie trafione zadaje dodatkowe 2k6 obrażeń promienistych. Trafiona istota zostaje naznaczona — rozświetlona, przez co nie może korzystać z niewidzialności przez minutę.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Calm Emotions": {
    name: "Calm Emotions",
    namePl: "Uspokojenie emocji",
    level: 2,
    school: "Enchantment",
    components: "V, S",
    description:
      "Wstrzymujesz silne emocje humanoidów w zasięgu 60 stóp: znasz spod wpływu zakochania, strachu i wściekłości. Zaklęcie trwa minutę, o ile utrzymujesz koncentrację — pozwala uspokoić wrogie tłumy.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Cloud of Daggers": {
    name: "Cloud of Daggers",
    namePl: "Chmura sztyletów",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Wypełniasz sześcian o boku 5 stóp wirującymi sztyletami. Istota wchodząca na ten obszar lub rozpoczynająca w nim turę wykonuje rzut obronny na Zręczność; nieudany oznacza 4k4 obrażeń tnących, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "4d4",
      damageType: "slashing",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Continual Flame": {
    name: "Continual Flame",
    namePl: "Wieczny płomień",
    level: 2,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Tworzysz płomień, który świeci jak pochodnia, nie zużywa paliwa i nie rozprzestrzenia ognia. Możesz nadać mu kolor i zagasić go w każdej chwili — efekt trwa, dopóki nie zostanie rozproszony.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Cordon of Arrows": {
    name: "Cordon of Arrows",
    namePl: "Krąg strzał",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przemieniasz cztery strzały lub bełty w pułapki unoszące się wokół punktu w zasięgu dotyku. Gdy istota zbliży się na 30 stóp, strzały wystrzeliwują, trafiając ją za 1k6 obrażeń przebijających każda — 8 godzin strzeże wybranego miejsca.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Crown of Madness": {
    name: "Crown of Madness",
    namePl: "Korona szaleństwa",
    level: 2,
    school: "Enchantment",
    components: "V, S",
    description:
      "Niewidzialna korona spowija głowę istoty w zasięgu 120 stóp; cel wykonuje rzut obronny na Mądrość. Nieudany oznacza, że na czas trwania zaklęcia istota kieruje swój gniew na wrogów — DM rozstrzyga narracyjnie, kogo zaatakuje.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Darkness": {
    name: "Darkness",
    namePl: "Ciemność",
    level: 2,
    school: "Evocation",
    components: "V, M",
    description:
      "Magiczna ciemność wypełnia sferę o promieniu 15 stóp: nie przenika przez nią nawet widzenie w ciemności, a światła wytwarzane przez zaklęcia niższego poziomu zostają w niej stłumione. Obszar utrzymuje się 10 minut, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Darkvision": {
    name: "Darkvision",
    namePl: "Widzenie w ciemności",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje widzenie w ciemności na 60 stóp na 8 godzin: w całkowitej ciemności widzi jak w przyćmionym świetle. Zaklęcie nie działa na istoty, które już posiadają widzenie w ciemności.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Detect Thoughts": {
    name: "Detect Thoughts",
    namePl: "Wykrywanie myśli",
    level: 2,
    school: "Divination",
    components: "V, S, M",
    description:
      "Przez minutę czytasz powierzchowne myśli istot w zasięgu 30 stóp i wykrywasz obecność rozumnych istot w promieniu 60 stóp. Głębsza penetracja umysłu wymaga rzutu obronnego na Mądrość celu — DM rozstrzyga, jakie informacje zdobywasz.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Dragon's Breath": {
    name: "Dragon's Breath",
    namePl: "Smoczy oddech",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje umiejętność wypluwania smoczego oddechu wybranego typu (kwas, lód, ogień, błyskawice lub trucizna) jako akcję dodatkową. Oddech zadaje 2k6 obrażeń w stożku 15 stóp — typ obrażeń ustala rzucający przy rzuceniu zaklęcia.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "fire",
      attack: true,
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Dust Devil": {
    name: "Dust Devil",
    namePl: "Diabeł pyłu",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz wir pyłu o szerokości 5 stóp, który porusza się w obrębie 60 stóp, ścigając wybrane cele. Istota kończąca turę w wirze wykonuje rzut obronny na Siłę; nieudany oznacza 1k8 obrażeń obuchowych, a większe istoty zostają odepchnięte.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "bludgeoning",
      attack: false,
      save: "strength",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Earthbind": {
    name: "Earthbind",
    namePl: "Związanie z ziemią",
    level: 2,
    school: "Transmutation",
    components: "V",
    description:
      "Wybierasz latającą istotę w zasięgu 300 stóp; cel wykonuje rzut obronny na Siłę. Nieudany oznacza, że jego prędkość lotu spada do 0 stóp na minutę — jeśli nie ma innego podparcia, opada bezpiecznie na ziemię.",
    effect: {
      kind: "none",
      range: "300 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Enhance Ability": {
    name: "Enhance Ability",
    namePl: "Wzmocnienie zdolności",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje przewagę przy testach jednej wybranej zdolności na godzinę — siły, zręczności, wytrzymałości, inteligencji, mądrości lub charyzmy (niektóre odmiany dają też dodatkowe efekty, np. dodatkowe punkty życia). Wymaga utrzymywania koncentracji.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Enlarge/Reduce": {
    name: "Enlarge/Reduce",
    namePl: "Powiększenie/Pomniejszenie",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Powiększasz lub pomniejszasz istotę w zasięgu 30 stóp na minutę. Powiększony cel zyskuje przewagę przy testach Siły i dodatkowe 1k4 obrażeń, a pomniejszony ma utrudnienie przy testach Siły i zmniejszone obrażenia.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Enthrall": {
    name: "Enthrall",
    namePl: "Zniewolenie",
    level: 2,
    school: "Enchantment",
    components: "V, S",
    description:
      "Przykuwasz uwagę istot w zasięgu 60 stóp; cel wykonuje rzut obronny na Mądrość. Nieudany oznacza, że przez minutę istoty mają utrudnienie przy testach Postrzegania opartych na wzroku — DM rozstrzyga narracyjnie, kogo odwróci twoja mowa.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Find Steed": {
    name: "Find Steed",
    namePl: "Znajdź wierzchowca",
    level: 2,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz lojalnego, magicznego wierzchowca (konia, kucyka, wielbłąda lub inne zwierzę), który rozumie twoją mowę i w walce działa jako sojusznik. Po zniknięciu może zostać przywołany ponownie bez użycia czaru.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Find Traps": {
    name: "Find Traps",
    namePl: "Znajdź pułapki",
    level: 2,
    school: "Divination",
    components: "V, S",
    description:
      "Wyczuwasz obecność pułapek w zasięgu 120 stóp: zaklęcie ujawnia każdą pułapkę, którą można aktywować, i wskazuje jej przybliżone położenie. Nie ujawnia jednak, jak pułapka działa ani jak ją rozbroić.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Flame Blade": {
    name: "Flame Blade",
    namePl: "Ostrze ognia",
    level: 2,
    school: "Evocation",
    components: "V, S, M",
    description:
      "W twojej dłoni materializuje się ostrze z płomieni, które może atakować jako akcja dodatkowa. Wykonaj rzut ataku zaklęciem w zwarciu; trafienie zadaje 2k6 obrażeń ogniowych, a ostrze płonie przez minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "fire",
      attack: true,
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Flaming Sphere": {
    name: "Flaming Sphere",
    namePl: "Płonąca kula",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Kula ognia o średnicy 5 stóp toczy się w obrębie 60 stóp, a jako akcja dodatkowa możesz nią sterować. Istota, którą uderzy kula lub która zakończy turę w jej obszarze, wykonuje rzut obronny na Zręczność; nieudany oznacza 2k6 obrażeń ogniowych.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Gentle Repose": {
    name: "Gentle Repose",
    namePl: "Spokojny spoczynek",
    level: 2,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Chronisz zwłoki przed rozkładem i przed staniem się nieumarłymi na 10 dni; od tej pory do czasu ich wskrzeszenia nie odlicza się dni. Zaklęcie można rzucić jako rytuał, by bezpiecznie przetransportować poległego towarzysza.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "10 days",
      castingTime: "action",
    },
  },
  "Gust of Wind": {
    name: "Gust of Wind",
    namePl: "Podmuch wiatru",
    level: 2,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Wicher w linii 60 stóp (10 stóp szerokości) wieje z twojego położenia przez minutę, odrzucając i spowalniając istoty, które oprą się mu testem Siły. W obszarze wichru ataki z dystansu wykonuje się z utrudnieniem.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Heat Metal": {
    name: "Heat Metal",
    namePl: "Rozgrzanie metalu",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Metalowy przedmiot w zasięgu 60 stóp rozgrzewa się do czerwoności. Istota trzymająca go wykonuje rzut obronny na Kondycję; nieudany oznacza 2k8 obrażeń ogniowych, a do czasu twojej następnej tury jej ataki są wykonywane z utrudnieniem.",
    effect: {
      kind: "damage",
      dice: "2d8",
      damageType: "fire",
      attack: false,
      save: "constitution",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Invisibility": {
    name: "Invisibility",
    namePl: "Niewidzialność",
    level: 2,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Dotknięta istota staje się niewidzialna na godzinę, o ile utrzymujesz koncentrację: przedmioty noszone przez nią również znikają. Atak lub rzucenie zaklęcia kończy niewidzialność.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Knock": {
    name: "Knock",
    namePl: "Uderzenie",
    level: 2,
    school: "Transmutation",
    components: "V",
    description:
      "Głośne uderzenie otwiera zamknięte, zaryglowane lub zaczarowane drzwi w zasięgu 60 stóp, także te zamknięte zaklęciem Tajemny zamek (które zostaje stłumione na 10 minut). Dźwięk słychać w promieniu 300 stóp.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Levitate": {
    name: "Levitate",
    namePl: "Lewitacja",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Jedna istota lub przedmiot ważący do 500 funtów unosi się w pionie o maksymalnie 20 stóp i może być przemieszczany tylko w tych granicach. Efekt trwa 10 minut, o ile utrzymujesz koncentrację; cel może poruszać się w górę i w dół, odpychając się od podłoża.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Locate Animals or Plants": {
    name: "Locate Animals or Plants",
    namePl: "Odnajdywanie zwierząt lub roślin",
    level: 2,
    school: "Divination",
    components: "V, S, M",
    description:
      "Wypowiadasz nazwę gatunku zwierzęcia lub rośliny i poznajesz kierunek oraz odległość do najbliższej takiej istoty w promieniu 5 mil. Zaklęcie można rzucić jako rytuał — pomocne podczas poszukiwań w dziczy.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Locate Object": {
    name: "Locate Object",
    namePl: "Odnajdywanie przedmiotu",
    level: 2,
    school: "Divination",
    components: "V, S, M",
    description:
      "Opisujesz lub wskazujesz przedmiot, a przez 10 minut czujesz jego kierunek i odległość, o ile pozostaje w promieniu 1000 stóp. Zaklęcie nie działa na przedmiot noszony przez istotę, o ile nie wybierzesz konkretnego przedmiotu, który znasz.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Magic Mouth": {
    name: "Magic Mouth",
    namePl: "Magiczne usta",
    level: 2,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Na przedmiocie lub istocie pojawiają się niewidzialne usta, które po spełnieniu wybranego warunku wypowiadają zapisaną wiadomość (do 25 słów). Efekt trwa, dopóki nie zostanie rozproszony, a zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Magic Weapon": {
    name: "Magic Weapon",
    namePl: "Magiczna broń",
    level: 2,
    school: "Transmutation",
    components: "V, S",
    description:
      "Dotknięta nie magiczna broń staje się magiczna i zyskuje premię +1 do rzutów ataku i obrażeń na godzinę. Premia rośnie do +2 przy rzuceniu z 4. kręgu i +3 przy rzuceniu z 6. kręgu.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Mind Spike": {
    name: "Mind Spike",
    namePl: "Kolce umysłu",
    level: 2,
    school: "Divination",
    components: "V, S",
    description:
      "Prorocze widzenie przeszywa umysł celu w zasięgu 120 stóp: wykonuje on rzut obronny na Inteligencję. Nieudany oznacza 3k8 obrażeń psychicznych, a ty poznajesz jego położenie; do końca zaklęcia możesz ponawiać atak akcją dodatkową.",
    effect: {
      kind: "damage",
      dice: "3d8",
      damageType: "psychic",
      attack: false,
      save: "intelligence",
      range: "120 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Mirror Image": {
    name: "Mirror Image",
    namePl: "Złudne obrazy",
    level: 2,
    school: "Illusion",
    components: "V, S",
    description:
      "Trzy złudne kopie ciebie otaczają twoje ciało; każdy atak trafiający w ciebie najpierw trafia w obraz, który następnie znika (kolejne obrazy znikają po rzutach obronnych). Gdy znikną wszystkie, zaklęcie się kończy.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Misty Step": {
    name: "Misty Step",
    namePl: "Mglisty krok",
    level: 2,
    school: "Conjuration",
    components: "V",
    description:
      "Spowija cię krótki obłok srebrzystej mgły i teleportujesz się w dowolne widoczne miejsce w promieniu 30 stóp. Zaklęcie to akcja dodatkowa — możesz się wymknąć i nadal działać w tej samej turze.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "bonus",
    },
  },
  "Moonbeam": {
    name: "Moonbeam",
    namePl: "Promień księżyca",
    level: 2,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Srebrzysty promień księżyca oświetla walec o promieniu 5 stóp i wysokości 40 stóp w zasięgu 120 stóp. Istota wchodząca na ten obszar lub rozpoczynająca w nim turę wykonuje rzut obronny na Kondycję; nieudany oznacza 2k10 obrażeń promienistych.",
    effect: {
      kind: "damage",
      dice: "2d10",
      damageType: "radiant",
      attack: false,
      save: "constitution",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Pass without Trace": {
    name: "Pass without Trace",
    namePl: "Przejście bez śladu",
    level: 2,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Przez godzinę ty i sojusznicy w promieniu 30 stóp zyskujecie premię +10 do testów Skradania się i nie pozostawiacie śladów, których nie można zmazać. Idealne do nocnego przemknięcia obok strażników.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Phantasmal Force": {
    name: "Phantasmal Force",
    namePl: "Fantazmatyczna siła",
    level: 2,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz iluzję w umyśle istoty w zasięgu 60 stóp; cel wykonuje rzut obronny na Inteligencję. Nieudany oznacza, że postrzega iluzję jako rzeczywistość przez minutę — DM rozstrzyga jej skutki, w tym ewentualne obrażenia psychiczne.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Protection from Poison": {
    name: "Protection from Poison",
    namePl: "Ochrona przed trucizną",
    level: 2,
    school: "Abjuration",
    components: "V, S",
    description:
      "Dotknięta istota zyskuje odporność na obrażenia od trucizn, przewagę przy rzutach obronnych przeciwko zatruciu i nie może zostać otruta na godzinę. Jeśli jest już otruta, trucizna zostaje zneutralizowana.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Ray of Enfeeblement": {
    name: "Ray of Enfeeblement",
    namePl: "Promień osłabienia",
    level: 2,
    school: "Necromancy",
    components: "V, S",
    description:
      "Czarny promień wysysa siły z istoty w zasięgu 60 stóp; cel wykonuje rzut obronny na Kondycję. Nieudany oznacza, że przez minutę ataki bronią zależną od Siły zadają połowę obrażeń — DM rozstrzyga modyfikatory narracyjnie.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Rope Trick": {
    name: "Rope Trick",
    namePl: "Sztuczka z liną",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Linia wisi pionowo i kończy się niewidzialnym wejściem do pozawymiarowej przestrzeni, w której zmieści się do ośmiu istot. Stamtąd widać obszar wokół liny, ale nie odwrotnie — schronienie trwa godzinę.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Scorching Ray": {
    name: "Scorching Ray",
    namePl: "Palący promień",
    level: 2,
    school: "Evocation",
    components: "V, S",
    description:
      "Wypuszczasz trzy smugi ognia w cele w zasięgu 120 stóp; dla każdej wykonaj osobny rzut ataku zaklęciem. Każde trafienie zadaje 2k6 obrażeń ogniowych — możesz rozdzielić promienie między wiele celów.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "fire",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "See Invisibility": {
    name: "See Invisibility",
    namePl: "Widzenie niewidzialności",
    level: 2,
    school: "Divination",
    components: "V, S, M",
    description:
      "Przez godzinę widzisz niewidzialne istoty i przedmioty, a także stworzenia na płaszczyźnie eterycznej, jako półprzezroczyste kształty. Zaklęcie nie ujawnia jednak iluzji ani ukrytych istot — wymaga testów Postrzegania.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Shatter": {
    name: "Shatter",
    namePl: "Roztrzaskanie",
    level: 2,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Dźwiękowy wybuch rozbrzmiewa w punkcie w zasięgu 60 stóp, wypełniając sferę o promieniu 10 stóp. Każda istota w obszarze wykonuje rzut obronny na Kondycję; nieudany oznacza 3k8 obrażeń dźwiękowych, a przedmioty z kryształu i szkła mogą pęknąć.",
    effect: {
      kind: "damage",
      dice: "3d8",
      damageType: "thunder",
      attack: false,
      save: "constitution",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Silence": {
    name: "Silence",
    namePl: "Cisza",
    level: 2,
    school: "Illusion",
    components: "V, S",
    description:
      "W promieniu 20 stóp od wybranego punktu w zasięgu 120 stóp panuje absolutna cisza przez 10 minut: nie słychać tam żadnych dźwięków, a zaklęcia wymagające werbalnych komponentów nie mogą być rzucane. Idealne na strażników i magicznych rozmów.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Skywrite": {
    name: "Skywrite",
    namePl: "Pisanie na niebie",
    level: 2,
    school: "Transmutation",
    components: "V, S",
    description:
      "Chmury w polu widzenia układają się w słowa — nawet 10 słów widocznych z ziemi przez godzinę. Zaklęcie można rzucić jako rytuał, by przekazać wiadomość na wielką odległość; wymaga koncentracji, a deszcz i wiatr mogą je przerwać.",
    effect: {
      kind: "none",
      range: "Sight",
      duration: "1 day",
      castingTime: "action",
      concentration: true,
    },
  },
  "Spider Climb": {
    name: "Spider Climb",
    namePl: "Wspinaczka jak pająk",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje zdolność poruszania się po pionowych powierzchniach i sufitach, z wolnymi rękami, przez godzinę. Prędkość wspinaczki równa jest prędkości chodzenia — efekt wymaga utrzymywania koncentracji.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Spike Growth": {
    name: "Spike Growth",
    namePl: "Ostre ciernie",
    level: 2,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Ziemia w promieniu 20 stóp pokrywa się ukrytymi cierniami: obszar staje się trudnym terenem, a każda istota przemieszczająca się przez niego otrzymuje 2k4 obrażeń przebijających na każde 5 stóp. Ciernie są niewidoczne z daleka — DM rozstrzyga testy spostrzegawczości.",
    effect: {
      kind: "none",
      range: "150 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Suggestion": {
    name: "Suggestion",
    namePl: "Sugestia",
    level: 2,
    school: "Enchantment",
    components: "V, M",
    description:
      "Podsuwasz istocie w zasięgu 30 stóp rozsądnie brzmiącą sugestię; cel wykonuje rzut obronny na Mądrość. Nieudany oznacza, że istota wykona polecenie, o ile nie jest oczywiście szkodliwe — efekt trwa do 8 godzin, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Summon Beast": {
    name: "Summon Beast",
    namePl: "Przyzwanie bestii",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz bestialskiego ducha w wybrane miejsce w zasięgu 90 stóp; pojawia się on jako twoja istota sprzymierzona i wykonuje rozkazy w twoich turach. Duch walczy zadanymi trafieniami przez godzinę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Warding Bond": {
    name: "Warding Bond",
    namePl: "Więź ochronna",
    level: 2,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Zawierasz magiczną więź z dotkniętą istotą: jej Klasa Pancerza i rzuty obronne rosną o 1, a otrzymane przez nią obrażenia dzielisz na pół. Połowę obrażeń ponosisz ty — ryzyko równoważy obrona sojusznika.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Warding Wind": {
    name: "Warding Wind",
    namePl: "Wiatr ochronny",
    level: 2,
    school: "Evocation",
    components: "V",
    description:
      "Silny wiatr wiruje wokół ciebie w promieniu 10 stóp: ataki z dystansu wchodzące w obszar mają utrudnienie, dźwięki są stłumione, a opary i gazy zostają rozpędzone. Trwa 10 minut, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Web": {
    name: "Web",
    namePl: "Sieć",
    level: 2,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Gęste pajęczyny wypełniają sześcian o boku 20 stóp w zasięgu 60 stóp, tworząc trudny teren. Istoty wchodzące na ten obszar lub rozpoczynające w nim turę wykonują rzut obronny na Zręczność; nieudany oznacza stan spętania na czas trwania zaklęcia.",
    effect: {
      kind: "condition_apply",
      condition: "restrained",
      save: "dexterity",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Zone of Truth": {
    name: "Zone of Truth",
    namePl: "Strefa prawdy",
    level: 2,
    school: "Enchantment",
    components: "V, S",
    description:
      "Tworzysz sferę o promieniu 15 stóp w zasięgu 60 stóp; istoty w niej wykonują rzut obronny na Charyzmę. Nieudany oznacza, że przez 10 minut nie mogą świadomie kłamać — mogą milczeć lub mówić wymijająco, ale każda wypowiedź musi być prawdziwa.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
    },
  },
};
