import type { SpellDef } from "../spells.js";

export const SPELLS_L1: Record<string, SpellDef> = {
  Alarm: {
    name: "Alarm",
    namePl: "Alarm",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Wyznaczasz punkt w zasięgu 30 stóp i wiążesz z nim magiczny alarm. Gdy istota naruszy wyznaczony obszar, alarm ostrzega ciebie lub istotę, którą wskazałeś (rytuał).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Animal Friendship": {
    name: "Animal Friendship",
    namePl: "Przyjaźń ze zwierzęciem",
    level: 1,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Zwierzę o inteligencji 3 lub niższej, które widzisz w zasięgu 30 stóp, wykonuje rzut obronny na Mądrość; nieudany — jest oczarowane i nie może cię skrzywdzić. Zaklęcie trwa 24 godziny i wymaga zaoferowania zwierzęciu kęsa jedzenia.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Armor of Agathys": {
    name: "Armor of Agathys",
    namePl: "Zbroja Agathysa",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Otaczasz się magiczną lodową zbroją, która zapewnia 5 tymczasowych punktów życia. Istota trafiająca cię atakiem w zwarciu otrzymuje 5 obrażeń od zimna — DM rozstrzyga obrażenia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Arms of Hadar": {
    name: "Arms of Hadar",
    namePl: "Ramiona Hadara",
    level: 1,
    school: "Conjuration",
    components: "V, S",
    description:
      "Z twoich pleców wyrastają cieniste ramiona sięgające 10 stóp wokół ciebie. Każda istota w zasięgu wykonuje rzut obronny na Siłę; nieudany — 2k6 obrażeń nekrotycznych, udany — połowa.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "necrotic",
      attack: false,
      save: "strength",
      range: "Self (10 ft)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  Bane: {
    name: "Bane",
    namePl: "Zguba",
    level: 1,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Wybierasz do trzech istot w zasięgu 30 stóp; każda wykonuje rzut obronny na Charyzmę. Nieudany — cel odejmuje 1k4 od rzutów ataku i rzutów obronnych, dopóki utrzymujesz koncentrację (do 1 minuty).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Beast Bond": {
    name: "Beast Bond",
    namePl: "Więź ze zwierzęciem",
    level: 1,
    school: "Divination",
    components: "V, S, M",
    description:
      "Tworzysz telepatyczną więź z dotkniętym zwierzęciem na maksymalnie 1 minutę (koncentracja). Możecie ze sobą rozmawiać, a twoja przewaga nad zwierzęciem utrzymuje się bez rzutów.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Burning Hands": {
    name: "Burning Hands",
    namePl: "Płonące dłonie",
    level: 1,
    school: "Evocation",
    components: "V, S",
    description:
      "Z twoich dłoni bucha stożek ognia o długości 15 stóp. Każda istota w stożku wykonuje rzut obronny na Zręczność; nieudany — 3k6 obrażeń od ognia, udany — połowa.",
    effect: {
      kind: "damage",
      dice: "3d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "Self (15 ft cone)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Charm Person": {
    name: "Charm Person",
    namePl: "Czary uroku",
    level: 1,
    school: "Enchantment",
    components: "V, S",
    description:
      "Cel w zasięgu 30 stóp wykonuje rzut obronny na Mądrość; nieudany — traktuje cię jak przyjaznego znajomego na 1 godzinę. Zaklęcie kończy się, gdy ty lub twoi sojusznicy zaatakujecie cel.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Chromatic Orb": {
    name: "Chromatic Orb",
    namePl: "Chromatyczna kula",
    level: 1,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Rzucasz kulę energii w zasięgu 90 stóp i wykonujesz rzut ataku zaklęciem; trafienie zadaje 3k8 obrażeń wybranego typu (kwas, zimno, ogień, błyskawica, trucizna lub grzmot). Wymaga diamentu o wartości co najmniej 50 sztuk złota.",
    effect: {
      kind: "damage",
      dice: "3d8",
      damageType: "acid",
      attack: true,
      range: "90 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Color Spray": {
    name: "Color Spray",
    namePl: "Kolorowy deszcz",
    level: 1,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Stożek oślepiających barw o długości 15 stóp bucha z twoich dłoni. Istoty o łącznej liczbie punktów życia nie większej niż 6k10 zostają oślepione na 1 rundę — DM rozstrzyga, które cele zostają trafione.",
    effect: {
      kind: "none",
      range: "Self (15 ft cone)",
      duration: "1 round",
      castingTime: "action",
    },
  },
  Command: {
    name: "Command",
    namePl: "Rozkaz",
    level: 1,
    school: "Enchantment",
    components: "V",
    description:
      "Wypowiadasz jedno słowo rozkazu (np. „upaść”, „zbliżyć się”, „uciec”) skierowane do istoty w zasięgu 60 stóp. Cel wykonuje rzut obronny na Mądrość; nieudany — wykonuje rozkaz w swojej następnej turze.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Compelled Duel": {
    name: "Compelled Duel",
    namePl: "Wymuszony pojedynek",
    level: 1,
    school: "Enchantment",
    components: "V",
    description:
      "Cel w zasięgu 30 stóp wykonuje rzut obronny na Mądrość; nieudany — przez maksymalnie 1 minutę (koncentracja) ma utrudnienie w atakach innych niż przeciw tobie i musi zbliżać się do ciebie. Twoje ataki przeciwko niemu otrzymują przewagę.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Comprehend Languages": {
    name: "Comprehend Languages",
    namePl: "Rozumienie języków",
    level: 1,
    school: "Divination",
    components: "V, S, M",
    description:
      "Przez 1 godzinę rozumiesz dosłowne znaczenie każdego wypowiadanego lub pisanego języka, który usłyszysz lub zobaczysz. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Create or Destroy Water": {
    name: "Create or Destroy Water",
    namePl: "Stworzenie lub zniszczenie wody",
    level: 1,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Tworzysz do 10 galonów czystej wody w otwartym pojemniku w zasięgu 30 stóp albo niszczysz taką samą ilość wody. Woda może też spaść jako deszcz na obszar 30 × 30 stóp.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Detect Evil and Good": {
    name: "Detect Evil and Good",
    namePl: "Wykrycie zła i dobra",
    level: 1,
    school: "Divination",
    components: "V, S",
    description:
      "Przez maksymalnie 10 minut (koncentracja) wiesz, czy w promieniu 30 stóp znajduje się abolicja, celestial, elemental, fey, fiend, nieumarły lub święte miejsce. Zaklęcie nie wykrywa zwykłych osób o złych intencjach.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Detect Magic": {
    name: "Detect Magic",
    namePl: "Wykrycie magii",
    level: 1,
    school: "Divination",
    components: "V, S",
    description:
      "Przez maksymalnie 10 minut (koncentracja) odczuwasz obecność magii w promieniu 30 stóp i poznajesz jej szkołę. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Detect Poison and Disease": {
    name: "Detect Poison and Disease",
    namePl: "Wykrycie trucizny i choroby",
    level: 1,
    school: "Divination",
    components: "V, S, M",
    description:
      "Przez maksymalnie 10 minut (koncentracja) wyczuwasz trucizny i choroby w promieniu 30 stóp oraz rozpoznajesz ich rodzaj. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Disguise Self": {
    name: "Disguise Self",
    namePl: "Maska siebie",
    level: 1,
    school: "Illusion",
    components: "V, S",
    description:
      "Zmieniasz swój wygląd — wzrost, budowę, twarz, głos i ubiór — na 1 godzinę. Zauważenie iluzji wymaga udanego testu Inteligencji (Dochodzenie), a fizyczne dotknięcie zdradza oszustwo.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Dissonant Whispers": {
    name: "Dissonant Whispers",
    namePl: "Dysonansowe szepty",
    level: 1,
    school: "Enchantment",
    components: "V",
    description:
      "W umyśle celu w zasięgu 60 stóp rozbrzmiewa okropna melodia; cel wykonuje rzut obronny na Mądrość. Nieudany — 3k6 obrażeń psychicznych i cel ucieka od ciebie tak szybko, jak potrafi; udany — połowa obrażeń.",
    effect: {
      kind: "damage",
      dice: "3d6",
      damageType: "psychic",
      attack: false,
      save: "wisdom",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Divine Favor": {
    name: "Divine Favor",
    namePl: "Boska przychylność",
    level: 1,
    school: "Evocation",
    components: "V, S",
    description:
      "Twoja broń rozjarza się boskim blaskiem. Przez maksymalnie 1 minutę (koncentracja) twoje trafienia bronią zadają dodatkowe 1k4 obrażeń promienistych — DM rozstrzyga obrażenia przy trafieniu.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Ensnaring Strike": {
    name: "Ensnaring Strike",
    namePl: "Pętające uderzenie",
    level: 1,
    school: "Conjuration",
    components: "V",
    description:
      "Przed atakiem bronią przyzywasz cierniste pnącza; trafiony cel wykonuje rzut obronny na Siłę (akcja dodatkowa). Nieudany — cel jest spętany na 1 minutę (koncentracja) i może ponowić rzut, by się uwolnić.",
    effect: {
      kind: "condition_apply",
      condition: "restrained",
      save: "strength",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  Entangle: {
    name: "Entangle",
    namePl: "Poplątanie",
    level: 1,
    school: "Conjuration",
    components: "V, S",
    description:
      "Trawa i pnącza w kwadracie 20 × 20 stóp w zasięgu 90 stóp wyrastają, oplątując istoty. Każda z nich wykonuje rzut obronny na Siłę; nieudany — jest spętana i może ponowić rzut na początku swojej tury (koncentracja do 1 minuty).",
    effect: {
      kind: "condition_apply",
      condition: "restrained",
      save: "strength",
      range: "90 ft (20 ft square)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Expeditious Retreat": {
    name: "Expeditious Retreat",
    namePl: "Szybki odwrót",
    level: 1,
    school: "Transmutation",
    components: "V, S",
    description:
      "Zaczynasz biec z nadnaturalną szybkością: przez maksymalnie 10 minut (koncentracja) możesz jako akcję dodatkową wykonać akcję Szarży. Zaklęcie idealne do ucieczki lub szybkiego przemieszczania się.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Faerie Fire": {
    name: "Faerie Fire",
    namePl: "Feeryjny ogień",
    level: 1,
    school: "Evocation",
    components: "V",
    description:
      "Kostka 20 × 20 stóp w zasięgu 60 stóp rozświetla się w wybranym kolorze. Istoty, które nie wykonają udanego rzutu obronnego na Zręczność, są obrysowane światłem: ataki przeciwko nim mają przewagę (koncentracja do 1 minuty).",
    effect: {
      kind: "none",
      range: "60 ft (20 ft cube)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "False Life": {
    name: "False Life",
    namePl: "Fałszywe życie",
    level: 1,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Nekrotyczna energia otula cię, zapewniając 1k4+4 tymczasowych punktów życia na 1 godzinę. Tymczasowe punkty życia znikają po upływie czasu lub po ich utracie — DM rozstrzyga.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Feather Fall": {
    name: "Feather Fall",
    namePl: "Spowolnienie upadku",
    level: 1,
    school: "Transmutation",
    components: "V, M",
    description:
      "Reagując na upadek, spowalniasz do pięciu istot w zasięgu 60 stóp: tempo ich opadania zwalnia do 60 stóp na rundę (1 minuta). Zaklęcie rzucane jest reakcją, gdy ty lub sojusznik spadacie.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Find Familiar": {
    name: "Find Familiar",
    namePl: "Znajdź chowańca",
    level: 1,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Godzinny rytuał przywołuje ducha w kształcie małego zwierzęcia (np. kota, sowy, nietoperza), który ci służy i wykonuje twoje rozkazy. Chowaniec może być przywoływany i rozpraszany w dowolnej chwili.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Floating Disk": {
    name: "Floating Disk",
    namePl: "Pływający dysk",
    level: 1,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz dysk siły o średnicy 3 stóp, który towarzyszy ci przez 1 godzinę i unosi do 500 funtów ładunku. Dysk podąża za tobą w odległości 20 stóp i znika, gdy oddalisz się na ponad 100 stóp (rytuał).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Fog Cloud": {
    name: "Fog Cloud",
    namePl: "Chmura mgły",
    level: 1,
    school: "Conjuration",
    components: "V, S",
    description:
      "Tworzysz kulę gęstej mgły o promieniu 20 stóp w zasięgu 120 stóp; obszar jest mocno zasłonięty na maksymalnie 1 godzinę (koncentracja). Silny wiatr może rozwiać mgłę przed końcem czasu.",
    effect: {
      kind: "none",
      range: "120 ft (20 ft radius)",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  Goodberry: {
    name: "Goodberry",
    namePl: "Dobre jagody",
    level: 1,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Tworzysz dziesięć jagód w dłoni, z których każda przywraca 1 punkt życia istocie, która ją zje. Jagody zachowują moc przez 24 godziny — idealna zapasowa racja dla drużyny.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  Grease: {
    name: "Grease",
    namePl: "Tłuszcz",
    level: 1,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Śliski tłuszcz pokrywa kwadrat 10 × 10 stóp w zasięgu 60 stóp, tworząc trudny teren. Istota wchodząca na obszar lub rozpoczynająca w nim turę wykonuje rzut obronny na Zręczność; nieudany — pada (stan: powalony).",
    effect: {
      kind: "condition_apply",
      condition: "prone",
      save: "dexterity",
      range: "60 ft (10 ft square)",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Hail of Thorns": {
    name: "Hail of Thorns",
    namePl: "Grad cierni",
    level: 1,
    school: "Conjuration",
    components: "V",
    description:
      "Akcją dodatkową przywołujesz chmurę cierni przed atakiem bronią; trafiony cel i każda istota w promieniu 5 stóp od niego wykonują rzut obronny na Zręczność, otrzymując 1k10 obrażeń kłutych przy nieudanym rzucie (koncentracja do 1 minuty).",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Hellish Rebuke": {
    name: "Hellish Rebuke",
    namePl: "Piekielna nagana",
    level: 1,
    school: "Evocation",
    components: "V, S",
    description:
      "Reakcją na zranienie przez istotę w zasięgu 60 stóp otaczasz ją piekielnym płomieniem: cel wykonuje rzut obronny na Zręczność; nieudany — 2k10 obrażeń od ognia, udany — połowa. Uproszczenie mechaniki v1: akcja (reakcja rozstrzygana narracyjnie).",
    effect: {
      kind: "damage",
      dice: "2d10",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  Heroism: {
    name: "Heroism",
    namePl: "Bohaterstwo",
    level: 1,
    school: "Enchantment",
    components: "V, S",
    description:
      "Dotknięta istota jest odporna na strach i na początku każdej swojej tury otrzymuje tymczasowe punkty życia równe twojemu modyfikatorowi zdolności rzucania zaklęć — DM rozstrzyga punkty. Zaklęcie trwa do 1 minuty i wymaga koncentracji.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  Hex: {
    name: "Hex",
    namePl: "Urok",
    level: 1,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Akcją dodatkową przeklinasz istotę w zasięgu 90 stóp: twoje ataki przeciwko niej zadają dodatkowe 1k6 obrażeń nekrotycznych, a wybrana przez ciebie zdolność ma utrudnienie w testach (koncentracja do 1 godziny).",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Hunter's Mark": {
    name: "Hunter's Mark",
    namePl: "Znak łowcy",
    level: 1,
    school: "Divination",
    components: "V",
    description:
      "Akcją dodatkową oznaczasz istotę w zasięgu 90 stóp jako swoją zdobycz: twoje ataki przeciwko niej zadają dodatkowe 1k6 obrażeń kłutych (koncentracja do 1 godziny). Gdy cel zginie, w akcji dodatkowej możesz oznaczyć nową zdobycz.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "bonus",
      concentration: true,
    },
  },
  "Ice Knife": {
    name: "Ice Knife",
    namePl: "Lodowy nóż",
    level: 1,
    school: "Conjuration",
    components: "S, M",
    description:
      "Wypuszczasz sztylet z lodu w zasięgu 60 stóp; wykonaj rzut ataku zaklęciem — trafienie zadaje 1k10 obrażeń kłutych. Po uderzeniu lód pęka: cel i każda istota w promieniu 5 stóp wykonują rzut obronny na Zręczność, a nieudany oznacza 2k6 obrażeń od zimna — DM rozstrzyga, które cele trafia wybuch.",
    effect: {
      kind: "damage",
      dice: "1d10",
      damageType: "piercing",
      attack: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  Identify: {
    name: "Identify",
    namePl: "Identyfikacja",
    level: 1,
    school: "Divination",
    components: "V, S, M",
    description:
      "Dotykasz przedmiotu, który trzymasz przez cały czas rzucania zaklęcia, i poznajesz jego właściwości magiczne, sposób użycia oraz liczbę ładunków. Zaklęcie można rzucić jako rytuał; wymaga perły o wartości 100 sztuk złota.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Illusory Script": {
    name: "Illusory Script",
    namePl: "Iluzoryczne pismo",
    level: 1,
    school: "Illusion",
    components: "S, M",
    description:
      "Piszesz na kartce iluzoryczne pismo, które przez 10 dni wydaje się czytelnikowi zupełnie innym tekstem wskazanym przez ciebie. Osoba wybrana przy rzucaniu czyta prawdziwą treść; inni potrzebują udanego testu Inteligencji, by dostrzec oszustwo (rytuał).",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "10 days",
      castingTime: "action",
    },
  },
  Jump: {
    name: "Jump",
    namePl: "Skok",
    level: 1,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota przez 1 minutę skacze trzykrotnie dalej niż zwykle. Zaklęcie nie wymaga koncentracji, więc doskonale sprawdza się przed przeprawą lub przy manewrowaniu w walce.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
    },
  },
  Longstrider: {
    name: "Longstrider",
    namePl: "Długi krok",
    level: 1,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje na 1 godzinę dodatkowe 10 stóp szybkości. Zaklęcie nie wymaga koncentracji, a na poziomach wyższych niż pierwszy możesz objąć nim kolejną istotę za każdy dwa poziomy.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Mage Armor": {
    name: "Mage Armor",
    namePl: "Zbroja maga",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotykasz istoty, która nie nosi zbroi: przez 8 godzin jej klasa pancerza wynosi 13 + modyfikator Zręczności. Zaklęcie kończy się, gdy cel założy zbroję — DM rozstrzyga szczegóły narracyjne.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Magic Missile": {
    name: "Magic Missile",
    namePl: "Magiczny pocisk",
    level: 1,
    school: "Evocation",
    components: "V, S",
    description:
      "Trzy magiczne pociski lecą do wybranych celów w zasięgu 120 stóp; każdy trafia automatycznie i zadaje 1k4+1 obrażeń siłowych — pociski nigdy nie chybiają. Uproszczenie mechaniki v1: rzut ataku zaklęciem — DM rozstrzyga trafienia narracyjnie.",
    effect: {
      kind: "damage",
      dice: "1d4+1",
      damageType: "force",
      attack: true,
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Protection from Evil and Good": {
    name: "Protection from Evil and Good",
    namePl: "Ochrona przed złem i dobrem",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotknięta istota jest chroniona przez 10 minut (koncentracja) przed abolicjami, celestialami, elementalami, fey, fiendami i nieumarłymi. Wrogie istoty mają utrudnienie w atakach przeciwko niej, a ona nie może być przez nie kontrolowana (DM rozstrzyga efekty).",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Purify Food and Drink": {
    name: "Purify Food and Drink",
    namePl: "Oczyszczenie jedzenia i napojów",
    level: 1,
    school: "Transmutation",
    components: "V, S",
    description:
      "Oczyszczasz jedzenie i napoje w promieniu 10 stóp od siebie, usuwając z nich trucizny i choroby. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Self (10 ft radius)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Ray of Sickness": {
    name: "Ray of Sickness",
    namePl: "Promień choroby",
    level: 1,
    school: "Necromancy",
    components: "V, S",
    description:
      "Z palca wystrzeliwujesz wstrętny promień w zasięgu 60 stóp; wykonaj rzut ataku zaklęciem — trafienie zadaje 2k8 obrażeń od trucizny. Cel, który nie wykona udanego rzutu obronnego na Kondycję, zostaje także zatruty do końca twojej następnej tury (stan rozstrzyga DM).",
    effect: {
      kind: "damage",
      dice: "2d8",
      damageType: "poison",
      attack: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  Sanctuary: {
    name: "Sanctuary",
    namePl: "Sanktuarium",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Otaczasz wskazaną istotę w zasięgu 30 stóp aurą ochronną: każdy, kto ją zaatakuje, wykonuje rzut obronny na Mądrość, a nieudany — musi wybrać inny cel. Aura znika, gdy chroniona istota zaatakuje; trwa 1 minutę bez koncentracji.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Searing Smite": {
    name: "Searing Smite",
    namePl: "Płonące uderzenie",
    level: 1,
    school: "Evocation",
    components: "V",
    description:
      "Akcją dodatkową twoja broń żarzy się ogniem: następne trafienie bronią zadaje dodatkowe 1k6 obrażeń od ognia, a cel musi wykonać rzut obronny na Kondycję, by nie stanąć w płomieniach (koncentracja do 1 minuty).",
    effect: {
      kind: "damage",
      dice: "1d6",
      damageType: "fire",
      attack: true,
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  Shield: {
    name: "Shield",
    namePl: "Tarcza",
    level: 1,
    school: "Abjuration",
    components: "V, S",
    description:
      "Reakcją na trafienie lub magiczny pocisk otaczasz się niewidzialną tarczą: przez 1 rundę twoja klasa pancerza wzrasta o 5, a magiczne pociski nie mogą cię trafić. Uproszczenie mechaniki v1: akcja (reakcja rozstrzygana narracyjnie).",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 round",
      castingTime: "action",
    },
  },
  "Shield of Faith": {
    name: "Shield of Faith",
    namePl: "Tarcza wiary",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Świetlista tarcza krąży wokół wskazanej istoty w zasięgu 60 stóp, zwiększając jej klasę pancerza o 2 (koncentracja do 10 minut). Doskonała ochrona dla narażonego sojusznika na linii frontu.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Silent Image": {
    name: "Silent Image",
    namePl: "Cichy obraz",
    level: 1,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz iluzję obiektu, stworzenia lub sceny o wymiarach do 15 stóp w zasięgu 60 stóp; iluzja nie wydaje dźwięków. Możesz zmieniać obraz przez czas trwania (koncentracja do 10 minut), a istota może odkryć oszustwo testem Inteligencji (Dochodzenie).",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  Sleep: {
    name: "Sleep",
    namePl: "Sen",
    level: 1,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Rzucasz garść piasku z krainy snów: istoty w promieniu 15 stóp w zasięgu 60 stóp, których łączna liczba punktów życia nie przekracza 5k8, zapadają w sen (koncentracja do 1 minuty). DM rozstrzyga, które cele zasną; obrażenia budzą śpiących.",
    effect: {
      kind: "none",
      range: "60 ft (15 ft radius)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  Snare: {
    name: "Snare",
    namePl: "Pułapka",
    level: 1,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Tworzysz ukrytą magiczną pułapkę w zasięgu 30 stóp: gdy wskazana istota zbliży się na 30 stóp, możesz aktywować ją reakcją. Cel wykonuje rzut obronny na Zręczność, a nieudany — jest spętany na 1 minutę; pułapka działa do 8 godzin (DM rozstrzyga efekty narracyjnie).",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Speak with Animals": {
    name: "Speak with Animals",
    namePl: "Rozmowa ze zwierzętami",
    level: 1,
    school: "Divination",
    components: "V, S",
    description:
      "Przez 10 minut rozumiesz zwierzęta i możesz się z nimi porozumiewać: ich wiedza jest ograniczona inteligencją, ale chętnie dzielą się informacjami o okolicy. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Tasha's Hideous Laughter": {
    name: "Tasha's Hideous Laughter",
    namePl: "Okropny śmiech Tashy",
    level: 1,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Cel w zasięgu 30 stóp wybucha niekontrolowanym śmiechem: wykonuje rzut obronny na Mądrość, a nieudany — jest obezwładniony (stan: obezwładniony) na czas trwania. Cel może ponowić rzut obronny na końcu każdej swojej tury (koncentracja do 1 minuty).",
    effect: {
      kind: "condition_apply",
      condition: "incapacitated",
      save: "wisdom",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Thunderous Smite": {
    name: "Thunderous Smite",
    namePl: "Grzmotowe uderzenie",
    level: 1,
    school: "Evocation",
    components: "V",
    description:
      "Akcją dodatkową twoja broń rozbrzmiewa grzmotem: następne trafienie bronią zadaje dodatkowe 2k6 obrażeń od grzmotu, a cel musi wykonać rzut obronny na Siłę, by nie upaść (koncentracja do 1 minuty). DM rozstrzyga dodatkowe obrażenia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
  Thunderwave: {
    name: "Thunderwave",
    namePl: "Fala grzmotu",
    level: 1,
    school: "Evocation",
    components: "V, S",
    description:
      "Fala siły rozchodzi się z ciebie w kostce 15 × 15 stóp: każda istota wykonuje rzut obronny na Kondycję; nieudany — 2k8 obrażeń od grzmotu i odrzucenie o 10 stóp, udany — połowa obrażeń. Huk słyszalny jest w promieniu 300 stóp.",
    effect: {
      kind: "damage",
      dice: "2d8",
      damageType: "thunder",
      attack: false,
      save: "constitution",
      range: "Self (15 ft cube)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Unseen Servant": {
    name: "Unseen Servant",
    namePl: "Niewidzialny sługa",
    level: 1,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz niewidzialnego sługę w zasięgu 60 stóp, który przez 1 godzinę wykonuje proste zadania: sprzątanie, otwieranie drzwi, przenoszenie drobnych przedmiotów. Sługa nie potrafi atakować (rytuał).",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Witch Bolt": {
    name: "Witch Bolt",
    namePl: "Wiedźmi piorun",
    level: 1,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Błyskawica łączy cię z celem w zasięgu 30 stóp: wykonaj rzut ataku zaklęciem — trafienie zadaje 1k12 obrażeń od błyskawicy (koncentracja do 1 minuty). W kolejnych turach możesz w akcji dodatkowej ponownie zadać 1k12 obrażeń, dopóki cel jest w zasięgu.",
    effect: {
      kind: "damage",
      dice: "1d12",
      damageType: "lightning",
      attack: true,
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wrathful Smite": {
    name: "Wrathful Smite",
    namePl: "Gniewne uderzenie",
    level: 1,
    school: "Necromancy",
    components: "V",
    description:
      "Akcją dodatkową twoja broń spowija złowroga energia: następne trafienie bronią zadaje dodatkowe 1k6 obrażeń nekrotycznych, a cel musi wykonać rzut obronny na Mądrość, by nie zostać przestraszonym (koncentracja do 1 minuty). DM rozstrzyga dodatkowe obrażenia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "bonus",
      concentration: true,
    },
  },
};
