import type { SpellDef } from "../spells.js";

export const SPELLS_L89: Record<string, SpellDef> = {
  "Animal Shapes": {
    name: "Animal Shapes",
    namePl: "Formy zwierząt",
    level: 8,
    school: "Transmutation",
    components: "V, S",
    description:
      "Wybierasz dowolną liczbę chętnych istot w zasięgu 30 stóp: każda przyjmuje formę dowolnej bestii o współczynniku wyzwania nie większym niż 4 (do wyboru przez DM). Przemienione istoty zachowują cechy umysłowe i profil umiejętności, a zaklęcie trwa do 24 godzin, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "24 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Antimagic Field": {
    name: "Antimagic Field",
    namePl: "Pole antymagiczne",
    level: 8,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Wokół ciebie powstaje sfera antymagii o promieniu 10 stóp, w której zaklęcia nie działają, a magiczne przedmioty stają się zwykłymi przedmiotami. Konstrukty i nieumarli przywołani magią pozostają, lecz nie mogą przekroczyć granicy sfery, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self (10 ft)",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Antipathy/Sympathy": {
    name: "Antipathy/Sympathy",
    namePl: "Antypatia/Sympatia",
    level: 8,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Wybierasz istotę lub miejsce w zasięgu 60 stóp i wpajasz wskazanej grupie istot uczucie silnego pociągu (Sympatia) lub odrazy (Antypatia). Dotknięte istoty wykonują rzut obronny na Mądrość; porażka oznacza przymusowe zbliżanie się lub oddalanie przez 10 dni.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 days",
      castingTime: "action",
    },
  },
  "Clone": {
    name: "Clone",
    namePl: "Klon",
    level: 8,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Tworzysz inercyjną kopię istoty w zamkniętej wazie; klon dojrzewa w 120 dni i pozostaje bez życia, dopóki pierwotna istota nie zginie. Gdy to nastąpi, dusza ofiary przenosi się do klonu (koszt: klejnot o wartości 1000 sztuk złota — flavor).",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Special",
      castingTime: "action",
    },
  },
  "Control Weather": {
    name: "Control Weather",
    namePl: "Kontrola pogody",
    level: 8,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Zmieniasz pogodę na obszarze o promieniu 5 mil wokół siebie — od opadów, przez wiatr, po skrajne upały lub zamiecie — stopniowo w ciągu 1k4×10 minut. Zmiana trwa do 8 godzin, o ile utrzymujesz koncentrację; DM rozstrzyga wpływ pogody na scenę.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "8 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Demiplane": {
    name: "Demiplane",
    namePl: "Półpłaszczyzna",
    level: 8,
    school: "Conjuration",
    components: "S",
    description:
      "Tworzysz mgliste drzwi do pustej, sześciennej półpłaszczyzny o boku 30 stóp, która pozostaje otwarta przez 1 godzinę. Na każdej ścianie komory może pojawić się kolejne takie samo przejście — sposób na budowanie sieci prywatnych przestrzeni.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Dominate Monster": {
    name: "Dominate Monster",
    namePl: "Zdominowanie potwora",
    level: 8,
    school: "Enchantment",
    components: "V, S",
    description:
      "Istota w zasięgu 60 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza stan oczarowania na czas trwania zaklęcia, a cel ma przewagę, jeśli walczy z tobą lub twoimi sojusznikami. Masz telepatyczną więź z celem i wydajesz mu rozkazy bez akcji; cel ponawia rzut obronny za każdym razem, gdy otrzyma obrażenia.",
    effect: {
      kind: "condition_apply",
      condition: "charmed",
      save: "wisdom",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Earthquake": {
    name: "Earthquake",
    namePl: "Trzęsienie ziemi",
    level: 8,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Powodujesz wstrząsy w promieniu 100 stóp od wybranego punktu w zasięgu 500 stóp: istoty na ziemi wykonują rzut obronny na Zręczność, a porażka oznacza upadek (stan leżenia). Konstrukcje w zasięgu walą się, a teren staje się trudny — DM rozstrzyga zniszczenia i obrażenia od gruzów.",
    effect: {
      kind: "none",
      range: "500 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Feeblemind": {
    name: "Feeblemind",
    namePl: "Otępienie",
    level: 8,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Cel wykonuje rzut obronny na Inteligencję; nieudany oznacza 4k6 obrażeń psychicznych oraz spadek Inteligencji i Charyzmy do 1. Obezwładniona istota nie może rzucać zaklęć ani komunikować się sensownie — stan ten usuwa większe przywrócenie.",
    effect: {
      kind: "none",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
      concentration: true,
    },
  },
  "Glibness": {
    name: "Glibness",
    namePl: "Złotoustość",
    level: 8,
    school: "Enchantment",
    components: "V",
    description:
      "Przez godzinę wszystkie twoje testy Charyzmy dają wynik 15, a zaklęcia wykrywające kłamstwa traktują twoje wypowiedzi jako prawdę. DM rozstrzyga role społeczne — to zaklęcie dla negocjatorów i oszustów.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Holy Aura": {
    name: "Holy Aura",
    namePl: "Święta aura",
    level: 8,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Święta aura o promieniu 30 stóp otacza ciebie i wybrane istoty: mają one przewagę do rzutów obronnych, a ataki przeciwko nim wykonuje się z utrudnieniem. Złe istoty i nieumarli, którzy trafią cel w aurze, otrzymują 10k6 obrażeń promienistych, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self (30 ft)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Incendiary Cloud": {
    name: "Incendiary Cloud",
    namePl: "Płonąca chmura",
    level: 8,
    school: "Conjuration",
    components: "V, S",
    description:
      "Tworzysz chmurę gryzącego dymu o promieniu 20 stóp, silnie zasłaniającą widok; istoty w niej wykonują rzut obronny na Zręczność, a nieudany oznacza 10k8 obrażeń ogniowych. Chmura przemieszcza się 10 stóp od ciebie na początku każdej twojej tury, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "damage",
      dice: "10d8",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "150 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Maddening Darkness": {
    name: "Maddening Darkness",
    namePl: "Obłędna ciemność",
    level: 8,
    school: "Evocation",
    components: "V, M",
    description:
      "Sfera magicznej ciemności o promieniu 60 stóp, przeniknięta mrocznymi szeptami, pochłania światło magiczne i nieożywione; istoty w niej wykonują rzut obronny na Mądrość. Nieudany rzut oznacza 8k8 obrażeń psychicznych, a na początku swoich tur istoty ponawiają rzut, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "damage",
      dice: "8d8",
      damageType: "psychic",
      attack: false,
      save: "wisdom",
      range: "150 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Maze": {
    name: "Maze",
    namePl: "Labirynt",
    level: 8,
    school: "Conjuration",
    components: "S",
    description:
      "Cel wykonuje rzut obronny na Inteligencję; nieudany oznacza zesłanie w chaotyczny labirynt na innej płaszczyźnie, gdzie znika z pola walki na czas trwania zaklęcia. Istota może wydostać się tylko wykonując test Inteligencji (ST 20) w każdej swojej turze, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Mind Blank": {
    name: "Mind Blank",
    namePl: "Pusty umysł",
    level: 8,
    school: "Abjuration",
    components: "V, S",
    description:
      "Dotykasz istoty, która na 24 godziny zyskuje odporność na obrażenia psychiczne i nie może zostać oczarowana ani przestraszona. Zaklęcie jest tak potężne, że żadne zwykłe działanie nie może go zakończyć przed upływem czasu.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Power Word Stun": {
    name: "Power Word Stun",
    namePl: "Słowo mocy: Ogłuszenie",
    level: 8,
    school: "Enchantment",
    components: "V",
    description:
      "Wypowiadasz słowo mocy, które ogłusza wybraną istotę w zasięgu 60 stóp — bez rzutu obronnego, jeśli ma ona 150 punktów życia lub mniej. Ogłuszona istota ponawia rzut obronny na Kondycję na końcu każdej swojej tury, by odzyskać przytomność.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Telepathy": {
    name: "Telepathy",
    namePl: "Telepatia",
    level: 8,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Tworzysz telepatyczną więź z maksymalnie ośmioma istotami w promieniu 120 stóp: możesz wysyłać im wiadomości, a one mogą odpowiadać, niezależnie od wspólnego języka. Więź trwa 24 godziny — idealna do koordynacji drużyny na odległość.",
    effect: {
      kind: "none",
      range: "Self (120 ft)",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Trap the Soul": {
    name: "Trap the Soul",
    namePl: "Uwięzienie duszy",
    level: 8,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Wybierasz istotę w zasięgu 60 stóp; wykonuje ona rzut obronny na Charyzmę, a nieudany oznacza uwięzienie jej duszy w przygotowanym kamieniu szlachetnym o wartości co najmniej 1000 sztuk złota. Dusza pozostaje w kamieniu, dopóki nie zostanie on zniszczony lub zaklęcie rozproszone — ciało w tym czasie jest bezwładne.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Astral Projection": {
    name: "Astral Projection",
    namePl: "Projekcja astralna",
    level: 9,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Ty i do ośmiu chętnych istot opuszczacie ciała, tworząc srebrne łańcuchy prowadzące do świata astralnego; zniszczenie astralnego ciała nie zabija, lecz budzi śniącego. W świecie astralnym możecie podróżować między płaszczyznami, a zaklęcie trwa do powrotu w ciała (flavor: DM rozstrzyga podróż).",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "Special",
      castingTime: "action",
    },
  },
  "Foresight": {
    name: "Foresight",
    namePl: "Przewidywanie",
    level: 9,
    school: "Divination",
    components: "V, S, M",
    description:
      "Dotykasz istoty, która przez 8 godzin widzi fragmenty przyszłości: ma przewagę do rzutów ataku, rzutów obronnych i testów zdolności, a ataki przeciwko niej wykonuje się z utrudnieniem. Dodatkowo nie może być zaskoczona, dopóki zaklęcie trwa.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Gate": {
    name: "Gate",
    namePl: "Brama",
    level: 9,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Tworzysz portal łączący dwa miejsca na dowolnej płaszczyźnie istnienia, przez który istoty mogą przechodzić natychmiastowo; możesz też przyzwać przez niego wybraną istotę, która musi ci być posłuszna (rzut obronny na Mądrość). Portal trwa do minuty, o ile utrzymujesz koncentrację — lub pozostaje trwały, jeśli znasz sekwencję run stałej bramy.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Imprisonment": {
    name: "Imprisonment",
    namePl: "Uwięzienie",
    level: 9,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Wymawiając imię istoty w zasięgu 30 stóp, wykonuje ona rzut obronny na Mądrość; nieudany oznacza uwięzienie w jednej z sześciu form: senność, łańcuchy, uwięziona miniatura, szczelna sfera, ukryte więzienie lub miniaturowa sfera (do wyboru przez DM). Uwięziona istota nie może być odnaleziona przez zwykłe wróżby, a uwolnienie wymaga spełnienia warunków zaklęcia.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Invulnerability": {
    name: "Invulnerability",
    namePl: "Niewrażliwość",
    level: 9,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Przez 10 minut jesteś odporny na wszystkie obrażenia — żaden atak, zaklęcie ani efekt nie może ci zaszkodzić. Zaklęcie wymaga nieprzerwanej koncentracji i nie chroni przed stanami, które nie zadają obrażeń.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Mass Polymorph": {
    name: "Mass Polymorph",
    namePl: "Masowa polimorfia",
    level: 9,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przemieniasz dowolną liczbę istot w zasięgu 120 stóp w bestie o współczynniku wyzwania nie większym niż 8 (do wyboru przez DM). Przemienione istoty zachowują cechy umysłowe i profil umiejętności, a zaklęcie trwa do godziny, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Meteor Swarm": {
    name: "Meteor Swarm",
    namePl: "Rój meteorów",
    level: 9,
    school: "Evocation",
    components: "V, S",
    description:
      "Cztery kule ognia spadają z nieba w wybrane punkty w promieniu 1 mili; każda istota w promieniu 40 stóp od punktu uderzenia wykonuje rzut obronny na Zręczność. Nieudany rzut oznacza 20k6 obrażeń ogniowych i 20k6 obrażeń obuchowych, udany — połowę każdego rodzaju.",
    effect: {
      kind: "damage",
      dice: "20d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "1 mile",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Power Word Heal": {
    name: "Power Word Heal",
    namePl: "Słowo mocy: Uzdrowienie",
    level: 9,
    school: "Evocation",
    components: "V, S",
    description:
      "Wypowiadasz słowo mocy, które przywraca wybranej istocie w zasięgu 60 stóp pełne punkty życia bez żadnych ograniczeń — DM narracyjnie opisuje pełne uzdrowienie. Cel jest również uleczony ze ślepoty, głuchoty i paraliżu; zaklęcie nie wymaga rzutu obronnego.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Power Word Kill": {
    name: "Power Word Kill",
    namePl: "Słowo mocy: Zabójstwo",
    level: 9,
    school: "Enchantment",
    components: "V",
    description:
      "Wypowiadasz słowo mocy, które zabija wybraną istotę w zasięgu 60 stóp — bez rzutu obronnego, jeśli ma ona 100 punktów życia lub mniej. Istoty z większą liczbą punktów życia nie są dotknięte; DM rozstrzyga skutki natychmiastowej śmierci.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Prismatic Wall": {
    name: "Prismatic Wall",
    namePl: "Pryzmatyczna ściana",
    level: 9,
    school: "Abjuration",
    components: "V, S",
    description:
      "Tworzysz ścianę z siedmiu warstw światła o różnych kolorach, każda o odmiennym działaniu — od obrażeń po efekty specjalne, takie jak petryfikacja. Przejście przez ścianę wymaga pokonania każdej warstwy odpowiednim rzutem obronnym lub zaklęciem; DM rozstrzyga skutki warstw.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Shapechange": {
    name: "Shapechange",
    namePl: "Zmiana kształtu",
    level: 9,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przyjmujesz formę dowolnej istoty, którą widziałeś — z pełnymi statystykami i zdolnościami — zachowując swoją osobowość i cechy umysłowe. W każdej turze możesz przybrać nową formę, o ile utrzymujesz koncentrację przez maksymalnie godzinę.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Storm of Vengeance": {
    name: "Storm of Vengeance",
    namePl: "Burza zemsty",
    level: 9,
    school: "Conjuration",
    components: "V, S",
    description:
      "Ponad wybranym punktem w zasięgu wzroku formuje się burza o promieniu 360 stóp, działająca wielorundowo: ogłuszające grzmoty, kwaśny deszcz, grad i uderzenia piorunów. DM rozstrzyga skutki kolejnych rund burzy (m.in. rzuty obronne na Kondycję i Zręczność), o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Sight",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Time Stop": {
    name: "Time Stop",
    namePl: "Zatrzymanie czasu",
    level: 9,
    school: "Transmutation",
    components: "V",
    description:
      "Zatrzymujesz upływ czasu: poza tobą wszystko wstrzymuje się, a ty wykonujesz 1k4 + 1 dodatkowych tur. Możesz tylko poruszać się i wykonywać czynności inne niż atak lub rzucenie zaklęcia — DM rozstrzyga, co uda się zrobić w tym oknie.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "True Polymorph": {
    name: "True Polymorph",
    namePl: "Prawdziwa polimorfia",
    level: 9,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przemieniasz jedną istotę lub przedmiot w inną istotę lub przedmiot (do wyboru przez DM) na czas trwania zaklęcia; istota przyjmuje statystyki nowej formy. Jeśli utrzymasz koncentrację przez pełną godzinę, przemiana staje się trwała.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "True Resurrection": {
    name: "True Resurrection",
    namePl: "Prawdziwe wskrzeszenie",
    level: 9,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Dotykasz istoty zmarłej nie dłużej niż 200 lat temu i przywracasz ją do życia z pełnym poziomem życia — nawet bez ciała, o ile dusza jest wolna. Zaklęcie zamyka śmiertelne rany i przywraca brakujące części ciała (koszt: 25 000 sztuk złota — flavor).",
    effect: {
      kind: "revive",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
      fullHp: true,
    },
  },
  "Weird": {
    name: "Weird",
    namePl: "Osobliwość",
    level: 9,
    school: "Illusion",
    components: "V, S",
    description:
      "Tworzysz sferę o promieniu 30 stóp, w której istoty widzą najgorsze koszmary; każda z nich wykonuje rzut obronny na Mądrość, a nieudany oznacza stan przestraszenia. Na początku swoich tur przestraszone istoty ponawiają rzut, a porażka oznacza 4k10 obrażeń psychicznych.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wish": {
    name: "Wish",
    namePl: "Życzenie",
    level: 9,
    school: "Conjuration",
    components: "V",
    description:
      "Wypowiadasz najpotężniejsze życzenie, które zmienia rzeczywistość — najbezpieczniej powielając dowolne zaklęcie 8. poziomu lub niższe bez komponentów. Użycie wykraczające poza powielenie obarczone jest ryzykiem: DM interpretuje życzenie i nakłada konsekwencje, a do końca długiego odpoczynku każde kolejne rzucone przez ciebie zaklęcie zadaje ci 1k10 obrażeń nekrotycznych za poziom zaklęcia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
};
