import type { SpellDef } from "../spells.js";

export const SPELLS_L4: Record<string, SpellDef> = {
  "Arcane Eye": {
    name: "Arcane Eye",
    namePl: "Czarodziejskie oko",
    level: 4,
    school: "Divination",
    components: "V, S, M",
    description:
      "Niewidzialne, niewrażliwe oko unosi się w wybranym miejscu w zasięgu 30 stóp i przekazuje ci informacje wizualne — widzi we wszystkich kierunkach i w ciemności. Jako akcję dodatkową możesz przesunąć je o 30 stóp, ale solidna przeszkoda blokuje jego ruch.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Aura of Life": {
    name: "Aura of Life",
    namePl: "Aura życia",
    level: 4,
    school: "Abjuration",
    components: "V",
    description:
      "Od ciebie emanuje aura w promieniu 30 stóp, w której ty i sojusznicy jesteście odporni na obrażenia nekrotyczne, a wasze maksymalne punkty życia nie mogą być zmniejszane. Jeśli sojusznik z 0 punktami życia rozpocznie turę w aurze, odzyskuje 1 punkt życia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Black Tentacles": {
    name: "Black Tentacles",
    namePl: "Czarne macki",
    level: 4,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Wirujące, czarne macki wypełniają kwadrat o boku 20 stóp, tworząc z ziemi trudny teren. Każda istota w tym obszarze wykonuje rzut obronny na Siłę; nieudany oznacza 3k6 obrażeń obuchowych i stan spętania do końca zaklęcia.",
    effect: {
      kind: "damage",
      dice: "3d6",
      damageType: "bludgeoning",
      attack: false,
      save: "strength",
      range: "90 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Blight": {
    name: "Blight",
    namePl: "Zażenie",
    level: 4,
    school: "Necromancy",
    components: "V, S",
    description:
      "Cel w zasięgu 30 stóp wykonuje rzut obronny na Kondycję; nieudany oznacza 8k8 obrażeń nekrotycznych, udany — połowę. Rośliny automatycznie nie zdają tego rzutu, a nieistotowa roślina bez rzutu usycha i ginie.",
    effect: {
      kind: "damage",
      dice: "8d8",
      damageType: "necrotic",
      attack: false,
      save: "constitution",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Charm Monster": {
    name: "Charm Monster",
    namePl: "Zaurocz potwora",
    level: 4,
    school: "Enchantment",
    components: "V, S",
    description:
      "Jeden potwór w zasięgu 30 stóp wykonuje rzut obronny na Mądrość (z przewagą, jeśli z nim walczycie); nieudany oznacza, że na godzinę zostaje oczarowany i odnosi się do ciebie przyjaźnie. Oczarowanie kończy się, gdy ty lub sojusznicy go zaatakujecie, a po ustaniu efektu cel wie, że został oczarowany.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Compulsion": {
    name: "Compulsion",
    namePl: "Przymus",
    level: 4,
    school: "Enchantment",
    components: "V, S",
    description:
      "Każdy wybrany przez ciebie cel w zasięgu 30 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza oczarowanie na czas trwania zaklęcia. Jako akcję dodatkową wyznaczasz kierunek, w którym oczarowane istoty muszą w swojej turze przesunąć się najbezpieczniejszą trasą, a po ruchu mogą powtórzyć rzut obronny.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Confusion": {
    name: "Confusion",
    namePl: "Zamęt",
    level: 4,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Każda istota w kuli o promieniu 10 stóp w zasięgu 90 stóp wykonuje rzut obronny na Mądrość. Nieudany oznacza, że cel nie może używać akcji dodatkowych ani reakcji i na początku każdej swojej tury rzuca 1k10, by ustalić swoje zachowanie — od bezczynności po atak w zwarciu na losową istotę.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Conjure Minor Elementals": {
    name: "Conjure Minor Elementals",
    namePl: "Przyzwanie mniejszych żywiołaków",
    level: 4,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz duchy Żywiołów krążące wokół ciebie w promieniu 15 stóp: każdy twój atak trafiający istotę w tym obszarze zadaje dodatkowe 2k8 obrażeń (kwasowych, zimnych, ogniowych lub od błyskawic, do wyboru). Ziemia w aurze jest trudnym terenem dla twoich wrogów.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Conjure Woodland Beings": {
    name: "Conjure Woodland Beings",
    namePl: "Przyzwanie istot leśnych",
    level: 4,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz duchy natury krążące wokół ciebie w promieniu 10 stóp; istota wchodząca w aurę lub kończąca w niej turę wykonuje rzut obronny na Mądrość. Nieudany oznacza 5k8 obrażeń siłowych, udany — połowę, a ty możesz dodatkowo używać akcji Ucieczka jako akcji dodatkowej.",
    effect: {
      kind: "damage",
      dice: "5d8",
      damageType: "force",
      attack: false,
      save: "wisdom",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Control Water": {
    name: "Control Water",
    namePl: "Kontrola wody",
    level: 4,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Kontrolujesz wodę w sześcianie o boku do 100 stóp w zasięgu 300 stóp, wybierając jeden z efektów: powódź, rozdzielenie wód, zmianę nurtu lub wir. Efekt trwa 10 minut, o ile utrzymujesz koncentrację, a w kolejnych turach możesz go zmienić lub powtórzyć.",
    effect: {
      kind: "none",
      range: "300 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Death Ward": {
    name: "Death Ward",
    namePl: "Stróż śmierci",
    level: 4,
    school: "Abjuration",
    components: "V, S",
    description:
      "Dotknięta istota zyskuje ochronę przed śmiercią na 8 godzin: pierwszy raz, gdy spadłaby do 0 punktów życia, zamiast tego kończy z 1 punktem życia, a zaklęcie się kończy. Efekt chroni także przed skutkiem, który zabiłby natychmiast bez zadawania obrażeń.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Dimension Door": {
    name: "Dimension Door",
    namePl: "Wymiarowe drzwi",
    level: 4,
    school: "Conjuration",
    components: "V",
    description:
      "Teleportujesz się w dowolne miejsce w zasięgu 500 stóp — widziane, wyobrażone lub opisane kierunkiem i odległością. Możesz zabrać ze sobą jedną chętną istotę stojącą w promieniu 5 stóp; jeśli miejsce docelowe byłoby zajęte, teleportacja nie udaje się, a wy ponosicie 4k6 obrażeń siłowych.",
    effect: {
      kind: "none",
      range: "500 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Divination": {
    name: "Divination",
    namePl: "Wróżby",
    level: 4,
    school: "Divination",
    components: "V, S, M",
    description:
      "Kontaktujesz się z bóstwem lub jego sługami i zadajesz jedno pytanie o cel, wydarzenie lub działalność w ciągu najbliższych 7 dni; DM odpowiada prawdą, niekiedy krótkim zdaniem lub zagadkową rymowanką. Zaklęcie można rzucić jako rytuał, a każde kolejne rzucenie przed długim odpoczynkiem ma 25% szans na brak odpowiedzi.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Dominate Beast": {
    name: "Dominate Beast",
    namePl: "Zdominowanie bestii",
    level: 4,
    school: "Enchantment",
    components: "V, S",
    description:
      "Jedna bestia w zasięgu 60 stóp wykonuje rzut obronny na Mądrość (z przewagą, jeśli z nią walczycie); nieudany oznacza oczarowanie na czas trwania zaklęcia. Utrzymujesz z celem telepatyczną więź i rozkazujesz mu bez użycia akcji, a przy każdych otrzymanych obrażeniach może powtórzyć rzut obronny.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Fabricate": {
    name: "Fabricate",
    namePl: "Wytwarzanie",
    level: 4,
    school: "Transmutation",
    components: "V, S",
    description:
      "Przez 10 minut przekształcasz surowe materiały w gotowy przedmiot z tego samego materiału: z drzew most, z lnu linę, z wełny ubranie. Przedmiot może być duży lub mniejszy (metal i kamień — tylko średni), ale nie możesz stworzyć żywych istot ani magicznych przedmiotów.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Faithful Hound": {
    name: "Faithful Hound",
    namePl: "Wierny pies",
    level: 4,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz widmowego psa stróżującego w widocznym miejscu w zasięgu 30 stóp; tylko ty go widzisz, jest bezcielesny i niezniszczalny. Gdy istota zbliży się na 30 stóp bez podanego hasła, pies szczeka, a na początku twoich tur gryzie wroga w promieniu 5 stóp — cel wykonuje rzut obronny na Zręczność, nieudany oznacza 4k8 obrażeń siłowych.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Fire Shield": {
    name: "Fire Shield",
    namePl: "Ognista tarcza",
    level: 4,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Płomienie otaczają twoje ciało na 10 minut, rzucając jasne światło; wybierasz tarczę ciepła (odporność na zimno) lub tarczę chłodu (odporność na ogień). Istota, która trafi cię atakiem w zwarciu w promieniu 5 stóp, otrzymuje 2k8 obrażeń ogniowych lub zimnych.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Freedom of Movement": {
    name: "Freedom of Movement",
    namePl: "Swoboda ruchu",
    level: 4,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotknięta istota przez godzinę porusza się bez przeszkód: trudny teren jej nie spowalnia, a zaklęcia nie mogą zmniejszyć jej prędkości ani wywołać paraliżu czy spętania. Zyskuje też prędkość pływania równą swojej prędkości i automatycznie uwalnia się z niemagicznych więzów.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Giant Insect": {
    name: "Giant Insect",
    namePl: "Ogromny owad",
    level: 4,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz ogromną stonogę, pająka lub osę, która walczy u twojego boku przez 10 minut, o ile utrzymujesz koncentrację. Owad działa zaraz po twojej turze i wykonuje twoje rozkazy słowne, a znika przy 0 punktach życia lub po ustaniu zaklęcia.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Greater Invisibility": {
    name: "Greater Invisibility",
    namePl: "Większa niewidzialność",
    level: 4,
    school: "Illusion",
    components: "V, S",
    description:
      "Dotknięta istota staje się niewidzialna na minutę, o ile utrzymujesz koncentrację. W przeciwieństwie do zwykłej niewidzialności efekt nie kończy się po ataku ani rzuceniu zaklęcia — cel może walczyć, pozostając niewidocznym.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Hallucinatory Terrain": {
    name: "Hallucinatory Terrain",
    namePl: "Halucynacyjny teren",
    level: 4,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Sprawiasz, że naturalny teren w sześcianie o boku 150 stóp w zasięgu 300 stóp wygląda, brzmi i pachnie jak inny teren — otwarte pole jak bagno, skarpa jak łagodne zbocze. Dotyk zdradza iluzję, a istota badająca obszar testem Inteligencji może ją przejrzeć; efekt trwa 24 godziny.",
    effect: {
      kind: "none",
      range: "300 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Ice Storm": {
    name: "Ice Storm",
    namePl: "Burza lodowa",
    level: 4,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Grad spada w walcu o promieniu 20 stóp i wysokości 40 stóp w zasięgu 300 stóp; każda istota w nim wykonuje rzut obronny na Zręczność. Nieudany oznacza 2k10 obrażeń obuchowych i 4k6 obrażeń zimna, a kamienie gradu zmieniają ziemię w trudny teren do końca twojej następnej tury.",
    effect: {
      kind: "damage",
      dice: "2d10",
      damageType: "bludgeoning",
      attack: false,
      save: "dexterity",
      range: "300 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Locate Creature": {
    name: "Locate Creature",
    namePl: "Odnajdywanie istoty",
    level: 4,
    school: "Divination",
    components: "V, S, M",
    description:
      "Opisujesz lub nazywasz istotę, którą znasz, i przez godzinę czujesz kierunek do niej, o ile jest w promieniu 1000 stóp i czujesz to na odległość. Zaklęcie nie wykrywa istoty zmienionej magicznie ani oddzielonej od ciebie warstwą ołowiu.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Phantasmal Killer": {
    name: "Phantasmal Killer",
    namePl: "Fantazmatyczny morderca",
    level: 4,
    school: "Illusion",
    components: "V, S",
    description:
      "Wykorzystujesz koszmary celu w zasięgu 120 stóp i tworzysz iluzję jego największych lęków, widoczną tylko dla niego; cel wykonuje rzut obronny na Mądrość. Nieudany oznacza 4k10 obrażeń psychicznych i utrudnienie przy testach zdolności i rzutach ataku, a cel ponawia rzut obronny na końcu każdej swojej tury — udany kończy zaklęcie.",
    effect: {
      kind: "damage",
      dice: "4d10",
      damageType: "psychic",
      attack: false,
      save: "wisdom",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Polymorph": {
    name: "Polymorph",
    namePl: "Przemiana",
    level: 4,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Cel w zasięgu 60 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza, że na czas trwania zmienia się w bestię o współczynniku wyzwania nie wyższym niż jego własny. Statystyki celu zastępują statystyki bestii (zachowuje punkty życia, typ istoty i osobowość), ale nie może mówić ani rzucać zaklęć.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Private Sanctum": {
    name: "Private Sanctum",
    namePl: "Prywatne sanktuarium",
    level: 4,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Czynisz sześcienny obszar o boku od 5 do 100 stóp w zasięgu 120 stóp magicznie bezpiecznym na 24 godziny, wybierając zabezpieczenia: dźwięk nie przenika, ściany są ciemne i zamglone, zaklęcia wróżby nie działają, a teleportacja i podróże między płaszczyznami są zablokowane. Codzienne rzucanie w tym samym miejscu przez 365 dni czyni efekt stałym.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Resilient Sphere": {
    name: "Resilient Sphere",
    namePl: "Sprężysta kula",
    level: 4,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Błyszcząca kula zamyka istotę lub przedmiot średniego rozmiaru lub mniejszy w zasięgu 30 stóp — niechętna istota wykonuje rzut obronny na Zręczność. Nic nie przenika przez barierę, kula jest odporna na wszystkie obrażenia, a uwięziona istota może toczyć kulę z prędkością połowy swojej.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Secret Chest": {
    name: "Secret Chest",
    namePl: "Tajemna skrzynia",
    level: 4,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Ukrywasz skrzynię wraz z zawartością na Płaszczyźnie Eterycznej, dotykając jej miniaturowej repliki, która służy za komponent materialny. Dotykając repliki, możesz przywołać skrzynię lub odesłać ją z powrotem jako akcję magiczną; efekt trwa, dopóki nie zostanie rozproszony.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Stone Shape": {
    name: "Stone Shape",
    namePl: "Kształtowanie kamienia",
    level: 4,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotykasz kamiennego obiektu średniego rozmiaru lub sekcji kamienia o wymiarach do 5 stóp i nadajesz mu dowolny kształt: broń, posąg, skrytkę albo przejście przez 5-stopową ścianę. Utworzony przedmiot może mieć do dwóch zawiasów i zasuwkę, ale nie drobniejsze mechanizmy.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Stoneskin": {
    name: "Stoneskin",
    namePl: "Kamienna skóra",
    level: 4,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Skóra dotkniętej istoty twardnieje jak kamień: przez godzinę jest ona odporna na obrażenia obuchowe, przebijające i tnące. Efekt wymaga utrzymywania koncentracji i zużywa pył diamentowy o wartości 100 sztuk złota.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Vitriolic Sphere": {
    name: "Vitriolic Sphere",
    namePl: "Witriolowa kula",
    level: 4,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Świecąca kula kwasu uderza w punkt w zasięgu 150 stóp i eksploduje w kuli o promieniu 20 stóp; każda istota w obszarze wykonuje rzut obronny na Zręczność. Nieudany oznacza 10k4 obrażeń kwasowych i kolejne 5k4 na końcu następnej tury celu, udany — tylko połowę początkowych obrażeń.",
    effect: {
      kind: "damage",
      dice: "10d4",
      damageType: "acid",
      attack: false,
      save: "dexterity",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Wall of Fire": {
    name: "Wall of Fire",
    namePl: "Ściana ognia",
    level: 4,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Stwarzasz ścianę ognia o długości do 60 stóp, wysokości 20 stóp i grubości 1 stopy (lub pierścień o średnicy 20 stóp) na trwałej powierzchni w zasięgu 120 stóp. Istoty w obszarze ściany wykonują rzut obronny na Zręczność; nieudany oznacza 5k8 obrażeń ogniowych, a wybrana strona ściany zadaje 5k8 istotom kończącym turę w promieniu 10 stóp od niej.",
    effect: {
      kind: "damage",
      dice: "5d8",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
};
