import type { SpellDef } from "../spells.js";

export const SPELLS_L5: Record<string, SpellDef> = {
  "Animate Objects": {
    name: "Animate Objects",
    namePl: "Animacja przedmiotów",
    level: 5,
    school: "Transmutation",
    components: "V, S",
    description:
      "Ożywiasz do tylu niemagicznych przedmiotów, ile wynosi twój modyfikator zdolności rzucania zaklęć — każdy staje się konstruktem wykonującym twoje rozkazy. Jako akcję dodatkową możesz sterować stworzeniami w promieniu 500 stóp; DM rozstrzyga ataki ożywionych przedmiotów.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Antilife Shell": {
    name: "Antilife Shell",
    namePl: "Powołanie antyżycia",
    level: 5,
    school: "Abjuration",
    components: "V, S",
    description:
      "Aura w promieniu 10 stóp wokół ciebie uniemożliwia innym istotom — poza konstruktami i nieumarłymi — przechodzenie i sięganie przez nią. Zaklęcie trwa do godziny, o ile utrzymujesz koncentrację — idealne do odcięcia wrogów w ciasnej walce.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Arcane Hand": {
    name: "Arcane Hand",
    namePl: "Tajemna dłoń",
    level: 5,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Tworzysz Dużą, świecącą dłoń z magicznej energii, którą sterujesz jak własną; jako akcję dodatkową może uderzyć cel — rzut ataku zaklęciem, trafienie zadaje 5k8 obrażeń siłowych. Dłoń może też pchnąć lub pochwycić wroga w promieniu 5 stóp (znana dawniej jako Dłoń Bigby'ego).",
    effect: {
      kind: "damage",
      dice: "5d8",
      damageType: "force",
      attack: true,
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Awaken": {
    name: "Awaken",
    namePl: "Przebudzenie",
    level: 5,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Po ośmiu godzinach rytuału dotykasz bestii lub rośliny o Inteligencji 3 lub niższej: zyskuje ona Inteligencję 10 i umiejętność mówienia w jednym znanym ci języku. Przebudzony cel ma stan oczarowania przez 30 dni lub do czasu, gdy wyrządzisz mu obrażenia.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Cloudkill": {
    name: "Cloudkill",
    namePl: "Chmura śmierci",
    level: 5,
    school: "Conjuration",
    components: "V, S",
    description:
      "Tworzysz sferę żółtozielonej mgły o promieniu 20 stóp, silnie zasłaniającą widok. Istoty w sferze wykonują rzut obronny na Kondycję; nieudany oznacza 5k8 obrażeń od trucizny, udany — połowę, a mgła przesuwa się 10 stóp od ciebie na początku twoich tur.",
    effect: {
      kind: "damage",
      dice: "5d8",
      damageType: "poison",
      attack: false,
      save: "constitution",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Commune": {
    name: "Commune",
    namePl: "Komunia",
    level: 5,
    school: "Divination",
    components: "V, S, M",
    description:
      "Kontaktujesz się z bóstwem lub jego pośrednikiem i zadajesz do trzech pytań, na które można odpowiedzieć „tak” lub „nie”, otrzymując poprawne odpowiedzi. Kolejne rzucenie przed ukończeniem długiego odpoczynku daje 25-procentową szansę braku odpowiedzi.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Commune with Nature": {
    name: "Commune with Nature",
    namePl: "Komunia z naturą",
    level: 5,
    school: "Divination",
    components: "V, S",
    description:
      "Komunikujesz się z duchami natury i poznajesz obszar w promieniu 3 mil (300 stóp w jaskiniach): wybierasz trzy fakty, np. lokalizacje osad, zbiorników wodnych czy portali na inne płaszczyzny. Zaklęcie nie działa na obszarach, gdzie naturę zastąpiła zabudowa.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Cone of Cold": {
    name: "Cone of Cold",
    namePl: "Stożek zimna",
    level: 5,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Wypuszczasz uderzenie mroźnego powietrza w stożku o długości 60 stóp. Każda istota w nim wykonuje rzut obronny na Kondycję; nieudany oznacza 8k8 obrażeń od zimna, udany — połowę, a istota zabita tym zaklęciem zamienia się w zamarznięty posąg.",
    effect: {
      kind: "damage",
      dice: "8d8",
      damageType: "cold",
      attack: false,
      save: "constitution",
      range: "Self (60 ft)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Conjure Elemental": {
    name: "Conjure Elemental",
    namePl: "Przyzwanie żywiołaka",
    level: 5,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz Dużego ducha z Żywiołowych Płaszczyzn, wybierając żywioł: powietrze (błyskawice), ziemię (grzmot), ogień lub wodę (zimno). Duch zadaje 8k8 obrażeń wybranego typu i spowalnia istoty w swoim pobliżu — DM rozstrzyga jego walkę.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Contact Other Plane": {
    name: "Contact Other Plane",
    namePl: "Kontakt z inną płaszczyzną",
    level: 5,
    school: "Divination",
    components: "V",
    description:
      "Mentalnie kontaktujesz się z istotą z innej płaszczyzny i wykonujesz rzut obronny na Inteligencję (ST 15): sukces pozwala zadać do pięciu pytań. Porażka oznacza 6k6 obrażeń psychicznych i stan obezwładnienia do końca długiego odpoczynku.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "Contagion": {
    name: "Contagion",
    namePl: "Zarażenie",
    level: 5,
    school: "Necromancy",
    components: "V, S",
    description:
      "Twój dotyk zadaje magiczną zarazę: cel wykonuje rzut obronny na Kondycję; nieudany oznacza 11k8 obrażeń nekrotycznych i stan zatrucia, a wybrana zdolność jest testowana z utrudnieniem. Po trzech nieudanych rzutach choroba trwa 7 dni, po trzech udanych — ustępuje.",
    effect: {
      kind: "damage",
      dice: "11d8",
      damageType: "necrotic",
      attack: false,
      save: "constitution",
      range: "Touch",
      duration: "7 days",
      castingTime: "action",
    },
  },
  "Creation": {
    name: "Creation",
    namePl: "Kreacja",
    level: 5,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz z cienia Mrocznej Otchłani przedmiot z materii roślinnej lub mineralnej, nie większy niż sześcian o boku 5 stóp — musi mieć formę, którą widziałeś. Czas trwania zależy od materiału: od 24 godzin (materia roślinna) do 1 minuty (adamantyt lub mithral).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Special",
      castingTime: "action",
    },
  },
  "Dispel Evil and Good": {
    name: "Dispel Evil and Good",
    namePl: "Rozproszenie zła i dobra",
    level: 5,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Przez minutę niebianie, żywiołaki, fey, fiendy i nieumarli mają utrudnienie przy atakach przeciwko tobie. Jako akcję magiczną możesz zakończyć zaklęcie, by uwolnić istotę od opętania lub odesłać jednego takiego wroga na jego macierzystą płaszczyznę (rzut obronny na Charyzmę).",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Dominate Person": {
    name: "Dominate Person",
    namePl: "Zdominowanie osoby",
    level: 5,
    school: "Enchantment",
    components: "V, S",
    description:
      "Humanoid w zasięgu 60 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza stan oczarowania na czas trwania zaklęcia, a cel ma przewagę, jeśli walczy z tobą lub twoimi sojusznikami. Masz telepatyczną więź z celem i wydajesz mu rozkazy bez akcji; cel ponawia rzut obronny za każdym razem, gdy otrzyma obrażenia.",
    effect: {
      kind: "condition_apply",
      condition: "charmed",
      save: "wisdom",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Dream": {
    name: "Dream",
    namePl: "Sen",
    level: 5,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Ty lub chętna istota wchodzicie w trans, by wkroczyć w sny znanej ci istoty z tej samej płaszczyzny i kształtować ich otoczenie. Jeśli cel śpi, posłaniec przekazuje wiadomość; przerażająca forma kończy się rzutem obronnym na Mądrość, a porażka oznacza 3k6 obrażeń psychicznych i brak korzyści z odpoczynku.",
    effect: {
      kind: "none",
      range: "Special",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Flame Strike": {
    name: "Flame Strike",
    namePl: "Uderzenie ognia",
    level: 5,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Kolumna ognia o promieniu 10 stóp i wysokości 40 stóp spada z nieba na wybrany punkt w zasięgu 60 stóp. Każda istota w walcu wykonuje rzut obronny na Zręczność; nieudany oznacza 5k6 obrażeń ogniowych i 5k6 promienistych, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "5d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Geas": {
    name: "Geas",
    namePl: "Zakaz",
    level: 5,
    school: "Enchantment",
    components: "V",
    description:
      "Wydajesz istocie w zasięgu 60 stóp słowny rozkaz; cel wykonuje rzut obronny na Mądrość, a nieudany oznacza stan oczarowania na 30 dni. Gdy oczarowana istota działa wbrew rozkazowi, otrzymuje 5k10 obrażeń psychicznych — nie częściej niż raz dziennie.",
    effect: {
      kind: "condition_apply",
      condition: "charmed",
      save: "wisdom",
      range: "60 ft",
      duration: "30 days",
      castingTime: "action",
    },
  },
  "Hallow": {
    name: "Hallow",
    namePl: "Poświęcenie",
    level: 5,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Po 24 godzinach rytuału poświęcasz obszar o promieniu do 60 stóp świętą lub bezbożną mocą. Wybrane typy istot nie mogą dobrowolnie wkroczyć na ten teren, a dodatkowy efekt — np. światło dzienne, ciemność czy cisza — trwa, dopóki zaklęcie nie zostanie rozproszone.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Hold Monster": {
    name: "Hold Monster",
    namePl: "Przytrzymanie potwora",
    level: 5,
    school: "Enchantment",
    components: "V, S, M",
    description:
      "Istota w zasięgu 90 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza paraliż na czas trwania zaklęcia, a cel ponawia rzut na końcu każdej swojej tury. Trafienia w zwarciu w sparaliżowanego celu są trafieniami krytycznymi.",
    effect: {
      kind: "condition_apply",
      condition: "paralyzed",
      save: "wisdom",
      range: "90 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Insect Plague": {
    name: "Insect Plague",
    namePl: "Plaga owadów",
    level: 5,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Rój szarańczy wypełnia sferę o promieniu 20 stóp, czyniąc ją trudnym terenem i lekko zasłaniając widok. Istoty w sferze wykonują rzut obronny na Kondycję; nieudany oznacza 4k10 obrażeń przebijających, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "4d10",
      damageType: "piercing",
      attack: false,
      save: "constitution",
      range: "300 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Legend Lore": {
    name: "Legend Lore",
    namePl: "Legendarne opowieści",
    level: 5,
    school: "Divination",
    components: "V, S, M",
    description:
      "Wymieniając słynne miejsce, osobę lub przedmiot, przywołujesz w umyśle streszczenie najważniejszych legend na jego temat. Wiedza jest dokładna, ale może być wyrażona metaforycznie; jeśli wybrany temat nie jest słynny, zaklęcie zawodzi.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Mass Cure Wounds": {
    name: "Mass Cure Wounds",
    namePl: "Masowe leczenie ran",
    level: 5,
    school: "Abjuration",
    components: "V, S",
    description:
      "Fala uzdrawiającej energii wypływa z wybranego punktu w zasięgu 60 stóp: do sześciu istot w promieniu 30 stóp odzyskuje 5k8 + modyfikator twojej zdolności rzucania zaklęć punktów życia. Leczenie nie może przekroczyć maksymalnego poziomu życia celu.",
    effect: {
      kind: "heal_all",
      dice: "5d8",
      mod: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Mislead": {
    name: "Mislead",
    namePl: "Zwodzenie",
    level: 5,
    school: "Illusion",
    components: "S",
    description:
      "Stajesz się niewidzialny, a w twoim miejscu pojawia się złudna kopia, którą sterujesz akcją magiczną — jest bezcielesna i niezniszczalna. Widzisz i słyszysz przez jej oczy i uszy; niewidzialność kończy się po twoim ataku, zadaniu obrażeń lub rzuceniu zaklęcia.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Modify Memory": {
    name: "Modify Memory",
    namePl: "Modyfikacja pamięci",
    level: 5,
    school: "Enchantment",
    components: "V, S",
    description:
      "Cel wykonuje rzut obronny na Mądrość; nieudany oznacza stan oczarowania, podczas którego jest nieprzytomny na otoczenie, a ty możesz zmienić jego pamięć wydarzeń z ostatnich 24 godzin. Jeśli cel otrzyma obrażenia, zaklęcie kończy się bez modyfikacji pamięci.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Passwall": {
    name: "Passwall",
    namePl: "Przejście przez ścianę",
    level: 5,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Na drewnianej, gipsowej lub kamiennej powierzchni w zasięgu 30 stóp pojawia się przejście o wymiarach do 5 stóp szerokości, 8 wysokości i 20 głębokości. Otwór trwa godzinę, a istoty w środku zostają bezpiecznie wypchnięte, gdy zniknie.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Planar Binding": {
    name: "Planar Binding",
    namePl: "Płaszczyznowe związanie",
    level: 5,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Po godzinie rytuału niebianin, żywiołak, fey lub fiend wykonuje rzut obronny na Charyzmę; nieudany oznacza związanie twoimi rozkazami na 24 godziny. Istota musi pozostać w zasięgu przez cały czas rzucania zaklęcia.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Raise Dead": {
    name: "Raise Dead",
    namePl: "Wskrzeszenie zmarłego",
    level: 5,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Dotyk przywraca do życia istotę zmarłą nie dłużej niż 10 dni temu, która nie była nieumarłym — z 1 punktem życia, neutralizując trucizny. Zaklęcie zamyka śmiertelne rany, ale nie odtwarza brakujących części ciała, a cel ma karę -4 do rzutów k20, malejącą o 1 po każdym długim odpoczynku.",
    effect: {
      kind: "revive",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
      fullHp: false,
    },
  },
  "Reincarnate": {
    name: "Reincarnate",
    namePl: "Reinkarnacja",
    level: 5,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Dotykasz martwego humanoida zmarłego nie dłużej niż 10 dni temu, a zaklęcie formuje dla jego duszy nowe, dorosłe ciało losowego gatunku (k10: od smoczycy po półnga). Odrodzony zachowuje wspomnienia i zdolności, lecz traci cechy poprzedniego gatunku.",
    effect: {
      kind: "revive",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Scrying": {
    name: "Scrying",
    namePl: "Widzenie na odległość",
    level: 5,
    school: "Divination",
    components: "V, S, M",
    description:
      "Widzisz i słyszysz wybraną istotę z tej samej płaszczyzny; cel wykonuje rzut obronny na Mądrość z modyfikatorem zależnym od twojej wiedzy o nim i fizycznego połączenia. Porażka tworzy niewidzialny czujnik podążający za celem, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Seeming": {
    name: "Seeming",
    namePl: "Pozory",
    level: 5,
    school: "Illusion",
    components: "V, S",
    description:
      "Zmieniasz iluzoryczny wygląd każdej wybranej istoty w zasięgu 30 stóp — wzrost, wagę, ciało i wyposażenie; niechętny cel może odrzucić efekt rzutem obronnym na Charyzmę. Iluzja nie wytrzymuje fizycznej inspekcji, a test Badania przeciwko twojej ST odkrywa przebranie.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Summon Dragon": {
    name: "Summon Dragon",
    namePl: "Przyzwanie smoka",
    level: 5,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz smoczego ducha, który materializuje się w wolnym miejscu w zasięgu 60 stóp i walczy jako twój sojusznik (statystyki smoczego ducha). Duch działa tuż po twojej turze i znika, gdy spadnie do 0 punktów życia lub zaklęcie się skończy.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Telekinesis": {
    name: "Telekinesis",
    namePl: "Telekineza",
    level: 5,
    school: "Transmutation",
    components: "V, S",
    description:
      "Przesuwasz i manipulujesz istotami lub przedmiotami siłą myśli: cel wykonuje rzut obronny na Siłę, a porażka oznacza przemieszczenie o maksymalnie 30 stóp i stan spętania do końca twojej następnej tury. Niewyposażony przedmiot przemieszczasz automatycznie.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Telepathic Bond": {
    name: "Telepathic Bond",
    namePl: "Więź telepatyczna",
    level: 5,
    school: "Divination",
    components: "V, S, M",
    description:
      "Tworzysz telepatyczną więź między maksymalnie ośmioma chętnymi istotami w zasięgu 30 stóp na godzinę. Połączone istoty mogą porozumiewać się telepatycznie na dowolną odległość, o ile pozostają na tej samej płaszczyźnie (znana dawniej jako Więź telepatyczna Rary'ego).",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Teleportation Circle": {
    name: "Teleportation Circle",
    namePl: "Krąg teleportacji",
    level: 5,
    school: "Conjuration",
    components: "V, M",
    description:
      "Rysujesz na ziemi krąg o promieniu 5 stóp z sigilami prowadzącymi do znanego ci stałego kręgu teleportacji na tej samej płaszczyźnie. Migoczący portal pozostaje otwarty do końca twojej następnej tury — każdy, kto wejdzie, natychmiast pojawia się w pobliżu celu.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "1 round",
      castingTime: "action",
    },
  },
  "Tree Stride": {
    name: "Tree Stride",
    namePl: "Krok drzewa",
    level: 5,
    school: "Conjuration",
    components: "V, S",
    description:
      "Wchodzisz do żywego drzewa i wychodzisz z innego drzewa tego samego gatunku w promieniu 500 stóp, wydając na to 5 stóp ruchu. Znasz położenie wszystkich takich drzew w zasięgu i możesz użyć tej zdolności tylko raz na turę.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wall of Force": {
    name: "Wall of Force",
    namePl: "Ściana siły",
    level: 5,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Niewidzialna ściana siły o grubości 1/4 cala powstaje w wybranym miejscu — jako płaszczyzna z dziesięciu paneli, kopuła lub kula o promieniu do 10 stóp. Nic nie może fizycznie przez nią przejść; jest odporna na wszystkie obrażenia i nie można jej rozproszyć (poza zaklęciem Rozpad).",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wall of Stone": {
    name: "Wall of Stone",
    namePl: "Kamienna ściana",
    level: 5,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Ściana z litego kamienia o grubości 6 cali i dziesięciu panelach 10x10 stóp wyrasta w wybranym miejscu, łącząc się z istniejącym kamieniem. Może przyjąć dowolny kształt — most, rampę czy barykadę — a każdy panel ma KP 15 i 30 punktów życia.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
};
