import type { SpellDef } from "../spells.js";

export const SPELLS_L6: Record<string, SpellDef> = {
  "Chain Lightning": {
    name: "Chain Lightning",
    namePl: "Łańcuchowe pioruny",
    level: 6,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Wypuszczasz piorun w widoczny cel w zasięgu 150 stóp; z niego trzy kolejne pioruny przeskakują do maksymalnie trzech innych celów w promieniu 30 stóp od pierwszego (każdy cel tylko raz). Każdy cel wykonuje rzut obronny na Zręczność; nieudany oznacza 10k8 obrażeń od błyskawic, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "10d8",
      damageType: "lightning",
      attack: false,
      save: "dexterity",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Circle of Death": {
    name: "Circle of Death",
    namePl: "Krąg śmierci",
    level: 6,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Negatywna energia rozchodzi się w kuli o promieniu 60 stóp od wybranego punktu w zasięgu 150 stóp. Każda istota w obszarze wykonuje rzut obronny na Kondycję; nieudany oznacza 8k8 obrażeń nekrotycznych, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "8d8",
      damageType: "necrotic",
      attack: false,
      save: "constitution",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Conjure Fey": {
    name: "Conjure Fey",
    namePl: "Przyzwanie fey",
    level: 6,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz Średniego ducha z Feywild, który przybiera wygląd wybranego stworzenia fey i pozostaje do 10 minut. Gdy się pojawia, możesz wykonać rzut ataku zaklęciem w zwarciu: trafienie zadaje 3k12 + modyfikator obrażeń psychicznych i stan przestraszenia; DM rozstrzyga ataki w kolejnych turach.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Contingency": {
    name: "Contingency",
    namePl: "Kontyngencja",
    level: 6,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Podczas 10-minutowego rzucania wybierasz zaklęcie 5. poziomu lub niższe, rzucane przy okazji za osobną kostkę — nie zadziała ono od razu, lecz dopiero po wystąpieniu wybranego przez ciebie wyzwalacza. Zaklęcie warunkowe działa tylko na ciebie, uruchamia się raz i wygasa; możesz mieć aktywne tylko jedno.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "10 days",
      castingTime: "action",
    },
  },
  "Create Undead": {
    name: "Create Undead",
    namePl: "Stworzenie nieumarłego",
    level: 6,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Tylko w nocy: wybierasz do trzech zwłok Małych lub Średnich humanoidów w zasięgu 10 stóp — każde staje się upiorem pod twoją kontrolą na 24 godziny. Akcją dodatkową możesz rozkazywać stworzeniom w promieniu 120 stóp; kolejne rzucenie przed końcem doby utrzymuje kontrolę nad upiorami.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Disintegrate": {
    name: "Disintegrate",
    namePl: "Rozpad",
    level: 6,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Zielony promień uderza w widoczny cel w zasięgu 60 stóp; cel wykonuje rzut obronny na Zręczność, a nieudany oznacza 10k6 + 40 obrażeń siłowych (dodatkowe +40 nie jest uwzględniane w rzucie kostek). Jeśli obrażenia sprowadzą cel do 0 punktów życia, obraca się on w szary pył i może zostać wskrzeszony tylko zaklęciem Prawdziwe zmartwychwstanie lub Życzenie.",
    effect: {
      kind: "damage",
      dice: "10d6",
      damageType: "force",
      attack: false,
      save: "dexterity",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Eyebite": {
    name: "Eyebite",
    namePl: "Złe spojrzenie",
    level: 6,
    school: "Necromancy",
    components: "V, S",
    description:
      "Twoje oczy stają się czarną otchłanią: wybrana widziana istota w promieniu 60 stóp wykonuje rzut obronny na Mądrość, a nieudany oznacza jeden z wybranych efektów na czas trwania — sen (nieprzytomność), panikę (przestraszenie) lub chorobę (zatrucie). W kolejnych turach akcją magiczną możesz zarażać inne cele, ale nie istoty, które zdały już rzut.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Find the Path": {
    name: "Find the Path",
    namePl: "Znajdź drogę",
    level: 6,
    school: "Divination",
    components: "V, S, M",
    description:
      "Magicznie wyczuwasz najprostszą fizyczną drogę do nazwanej lokalizacji, którą musisz znać; zaklęcie zawodzi, jeśli cel leży na innej płaszczyźnie lub się porusza. Podczas koncentracji znasz odległość i kierunek do celu, a na rozstajach dróg — która ścieżka jest najprostsza.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 day",
      castingTime: "action",
      concentration: true,
    },
  },
  "Flesh to Stone": {
    name: "Flesh to Stone",
    namePl: "Ciało w kamień",
    level: 6,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Próbujesz zamienić widoczną istotę w zasięgu 60 stóp w kamień: cel wykonuje rzut obronny na Kondycję, a nieudany oznacza stan spętania (uproszczenie: mechanika stosuje petryfikację, pełne zasady wymagają trzech nieudanych rzutów). Skamieniała istota pozostaje petryfikowana, dopóki zaklęcie nie zostanie przerwane — stan może zakończyć Większe przywrócenie.",
    effect: {
      kind: "condition_apply",
      condition: "petrified",
      save: "constitution",
      range: "60 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Forbiddance": {
    name: "Forbiddance",
    namePl: "Zakazany teren",
    level: 6,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Po 10-minutowym rytuale ochraniasz do 40 000 stóp kwadratowych podłogi na wysokość 30 stóp: istoty nie mogą się teleportować do tego obszaru ani dostać tam przez portale lub podróże międzyplanarne. Wybrane typy stworzeń wchodzące na teren lub kończące w nim turę otrzymują 5k10 obrażeń promienistych lub nekrotycznych, chyba że wypowiedzą ustalone hasło.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 day",
      castingTime: "action",
    },
  },
  "Freezing Sphere": {
    name: "Freezing Sphere",
    namePl: "Zamrażająca kula",
    level: 6,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Mroźna kula leci do wybranego punktu w zasięgu 300 stóp i eksploduje w kuli o promieniu 60 stóp. Każda istota w obszarze wykonuje rzut obronny na Kondycję; nieudany oznacza 10k6 obrażeń od zimna, udany — połowę, a uderzenie w zbiornik wody zamraża go do głębokości 6 cali.",
    effect: {
      kind: "damage",
      dice: "10d6",
      damageType: "cold",
      attack: false,
      save: "constitution",
      range: "300 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Globe of Invulnerability": {
    name: "Globe of Invulnerability",
    namePl: "Kula nietykalności",
    level: 6,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Wokół ciebie powstaje nieruchoma, migocząca bariera w promieniu 10 stóp na czas trwania zaklęcia. Zaklęcia 5. poziomu lub niższe rzucane spoza bariery nie mogą wpływać na nic wewnątrz niej — ani na istoty, ani na przedmioty.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Guards and Wards": {
    name: "Guards and Wards",
    namePl: "Straże i czary",
    level: 6,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Po godzinie rytuału ochraniasz do 2500 stóp kwadratowych podłogi na wysokość 20 stóp: korytarze wypełnia gęsta mgła, drzwi są magicznie zamknięte, a schody pełne pajęczyn. Dodatkowo umieszczasz wybrany efekt (tańczące światła, magiczne usta, cuchnącą chmurę, podmuch wiatru lub sugestię), a istoty znające hasło są odporne na wszystkie efekty.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Harm": {
    name: "Harm",
    namePl: "Zranienie",
    level: 6,
    school: "Necromancy",
    components: "V, S",
    description:
      "Uwalniasz złośliwą magię na widoczną istotę w zasięgu 60 stóp: cel wykonuje rzut obronny na Kondycję, a nieudany oznacza 14k6 obrażeń nekrotycznych i równoważne obniżenie maksymalnego poziomu życia (nie poniżej 1). Udany rzut zmniejsza obrażenia o połowę.",
    effect: {
      kind: "damage",
      dice: "14d6",
      damageType: "necrotic",
      attack: false,
      save: "constitution",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Heroes' Feast": {
    name: "Heroes' Feast",
    namePl: "Uczta bohaterów",
    level: 6,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz ucztę na powierzchni w pustym sześcianie 10 stóp obok siebie; do 12 istot spożywa ją przez godzinę, a korzyści trwają 24 godziny (zaklęcie nie zadaje obrażeń). Biesiadnicy zyskują odporność na obrażenia od trucizn oraz stany przestraszenia i zatrucia, a ich maksymalny poziom życia rośnie o 2k10 (odzyskują też tyle samo punktów życia).",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Instant Summons": {
    name: "Instant Summons",
    namePl: "Natychmiastowe przyzwanie",
    level: 6,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Dotykasz szafiru o wartości co najmniej 1000 sztuk złota i przedmiotu o wadze do 10 funtów, pozostawiając na nim niewidzialny znak i wpisując jego nazwę w kamień (znana dawniej jako Natychmiastowe przyzwanie Drawmija). Akcją magiczną możesz rozgnieść szafir, by przedmiot natychmiast znalazł się w twojej dłoni; jeśli trzyma go ktoś inny, poznajesz zamiast tego jego tożsamość i położenie.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Irresistible Dance": {
    name: "Irresistible Dance",
    namePl: "Nieodparty taniec",
    level: 6,
    school: "Enchantment",
    components: "V",
    description:
      "Cel w zasięgu 30 stóp wykonuje rzut obronny na Mądrość; nieudany oznacza stan oczarowania i komiczny taniec na czas trwania zaklęcia, z utrudnieniem na rzuty obronne na Zręczność i ataki (mechanika narracyjna — DM rozstrzyga modyfikatory). Udany rzut sprawia, że cel tańczy w miejscu do końca swojej następnej tury, a cel może ponowić rzut, poświęcając akcję na swojej turze.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Magic Jar": {
    name: "Magic Jar",
    namePl: "Magiczny słój",
    level: 6,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Twoje ciało zapada w stan katatoniczny, a dusza przenosi się do pojemnika (kryształ, klejnot lub relikwiarz o wartości co najmniej 500 sztuk złota) i może projektować się na odległość do 100 stóp. Możesz wrócić do ciała lub spróbować opętać widocznego humanoida — cel wykonuje rzut obronny na Charyzmę, a nieudany oznacza przeniesienie jego duszy do pojemnika i przejęcie jego ciała.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Mass Suggestion": {
    name: "Mass Suggestion",
    namePl: "Masowa sugestia",
    level: 6,
    school: "Enchantment",
    components: "V, M",
    description:
      "Sugerujesz opisany w maksymalnie 25 słowach przebieg czynności dwunastu lub mniej istotom w zasięgu 60 stóp, które cię słyszą i rozumieją; każda wykonuje rzut obronny na Mądrość, a nieudany oznacza stan oczarowania na 24 godziny. Sugestia musi brzmieć sensownie i nie może w oczywisty sposób szkodzić celom, a oczarowane istoty wypełniają ją najlepiej, jak potrafią.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Move Earth": {
    name: "Move Earth",
    namePl: "Poruszanie ziemią",
    level: 6,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Przekształcasz obszar ziemi o boku do 40 stóp w zasięgu 120 stóp: podnosisz lub obniżasz teren, kopiesz rowy, wznosisz ściany i filary, przy czym zmiany nie przekraczają połowy największego wymiaru obszaru i zachodzą przez 10 minut. Na koniec każdej takiej zmiany możesz wybrać nowy obszar; zaklęcie nie oddziałuje na naturalny kamień ani kamienne konstrukcje.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "2 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Planar Ally": {
    name: "Planar Ally",
    namePl: "Płaszczyznowy sprzymierzeniec",
    level: 6,
    school: "Conjuration",
    components: "V, S",
    description:
      "Błagasz kosmiczną potęgę (bóstwo, demonicznego księcia lub inną istotę), by przysłała ci niebianina, żywiołaka lub fiendę; stworzenie pojawia się w wolnym miejscu w zasięgu 60 stóp. Nie jest zobowiązane do posłuszeństwa — o przysługi trzeba negocjować i zapłacić (np. złotem, darem lub misją), a DM rozstrzyga cenę i zachowanie sojusznika.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Programmed Illusion": {
    name: "Programmed Illusion",
    namePl: "Zaprogramowana iluzja",
    level: 6,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz iluzję przedmiotu, istoty lub zjawiska nie większą niż sześcian o boku 30 stóp, która uaktywnia się po spełnieniu wybranego wyzwalacza widocznego lub słyszalnego w promieniu 30 stóp. Zaprogramowany spektakl trwa do 5 minut, a po zakończeniu iluzja pozostaje uśpiona przez 10 minut; fizyczny kontakt lub test Badania przeciwko twojej ST ujawnia jej naturę.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "Until dispelled",
      castingTime: "action",
    },
  },
  "Sunbeam": {
    name: "Sunbeam",
    namePl: "Promień słońca",
    level: 6,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Wystrzeliwujesz promień słońca w linii o długości 60 stóp i szerokości 5 stóp: każda istota w linii wykonuje rzut obronny na Kondycję, a nieudany oznacza 6k8 obrażeń promienistych i oślepienie do początku twojej następnej tury. Do końca zaklęcia akcją magiczną możesz tworzyć kolejne linie światła, a ponad tobą unosi się punkt jasnego światła słonecznego.",
    effect: {
      kind: "damage",
      dice: "6d8",
      damageType: "radiant",
      attack: false,
      save: "constitution",
      range: "Self (60 ft)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Transport via Plants": {
    name: "Transport via Plants",
    namePl: "Transport przez rośliny",
    level: 6,
    school: "Conjuration",
    components: "V, S",
    description:
      "Tworzysz magiczne połączenie między dużą lub większą nieożywioną rośliną w zasięgu 10 stóp a inną rośliną na tej samej płaszczyźnie, którą widziałeś lub dotknąłeś wcześniej. Przez minutę każda istota może wkroczyć do pierwszej rośliny i wyjść z docelowej, wydając na to 5 stóp ruchu.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "1 min",
      castingTime: "action",
    },
  },
  "True Seeing": {
    name: "True Seeing",
    namePl: "Prawdziwe widzenie",
    level: 6,
    school: "Divination",
    components: "V, S, M",
    description:
      "Dotykasz chętnej istoty: przez godzinę widzi ona prawdziwy obraz rzeczy zasięgiem prawdziwego widzenia do 120 stóp — niewidzialne istoty, ukryte przedmioty i magiczne iluzje. Zaklęcie pozwala także dostrzec normalną formę przekształconych stworzeń i ukryte zaklęcia w przedmiotach.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Wall of Ice": {
    name: "Wall of Ice",
    namePl: "Ściana lodu",
    level: 6,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Ściana lodu o grubości 1 stopy wyrasta na stałej powierzchni w zasięgu 120 stóp jako kopuła, kula lub dziesięć przylegających paneli 10x10 stóp. Istota, przez którą przechodzi ściana, jest wypychana na wybraną stronę i wykonuje rzut obronny na Zręczność; nieudany oznacza 10k6 obrażeń od zimna, a przejście przez powstały pas mroźnego powietrza zadaje 5k6 obrażeń od zimna.",
    effect: {
      kind: "damage",
      dice: "10d6",
      damageType: "cold",
      attack: false,
      save: "dexterity",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wall of Thorns": {
    name: "Wall of Thorns",
    namePl: "Ściana cierni",
    level: 6,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Ściana splątanych krzewów z ostrymi cierniami wyrasta na stałej powierzchni w zasięgu 120 stóp — do 60 stóp długości, 10 wysokości i 5 grubości albo okrąg o średnicy 20 stóp. Istoty w jej obszarze wykonują rzut obronny na Zręczność; nieudany oznacza 7k8 obrażeń przebijających, a poruszanie się przez ścianę kosztuje 4 stopy ruchu za każdą 1 stopę i zadaje 7k8 obrażeń tnących.",
    effect: {
      kind: "damage",
      dice: "7d8",
      damageType: "piercing",
      attack: false,
      save: "dexterity",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wind Walk": {
    name: "Wind Walk",
    namePl: "Krok wiatru",
    level: 6,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Ty i do dziesięciu chętnych istot w zasięgu 30 stóp przyjmujecie na 8 godzin postać chmur: lot z prędkością 300 stóp, odporność na obrażenia obuchowe, przebijające i tnące oraz odporność na stan leżenia. W tej formie można tylko wykonać akcję Szarża albo rozpocząć powrót do normalnej postaci — trwa on minutę, podczas której cel jest ogłuszony.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Word of Recall": {
    name: "Word of Recall",
    namePl: "Słowo powrotu",
    level: 6,
    school: "Conjuration",
    components: "V",
    description:
      "Ty i do pięciu chętnych istot w promieniu 5 stóp natychmiast teleportujecie się do wcześniej wyznaczonego sanktuarium, pojawiając się w najbliższym wolnym miejscu obok wybranego punktu. Sanktuarium wyznaczasz, rzucając to zaklęcie w danym miejscu (np. świątyni); rzucenie bez wyznaczonego sanktuarium nie daje żadnego efektu.",
    effect: {
      kind: "none",
      range: "5 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
};
