import type { SpellDef, SpellEffect } from "../spells.js";

export const SPELLS_L3: Record<string, SpellDef> = {
  "Animate Dead": {
    name: "Animate Dead",
    namePl: "Ożywienie umarłych",
    level: 3,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Dotykasz kości lub zwłok humanoida, ożywiając je jako szkielet lub zombie, które walczą pod twoją komendą przez 24 godziny. Użycie zaklęcia z wyższego kręgu przywołuje dodatkowe istoty — DM rozstrzyga sterowanie nimi w walce.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Aura of Vitality": {
    name: "Aura of Vitality",
    namePl: "Aura żywotności",
    level: 3,
    school: "Evocation",
    components: "V",
    description:
      "Uzdrawiająca aura otacza cię w promieniu 30 stóp; jako akcję dodatkową przywracasz jednej istocie w jej obszarze 2k6 punktów życia. Efekt trwa minutę, o ile utrzymujesz koncentrację — wielokrotne leczenie w kolejnych turach rozstrzyga DM.",
    effect: {
      kind: "none",
      range: "Self (30 ft)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Beacon of Hope": {
    name: "Beacon of Hope",
    namePl: "Latarnia nadziei",
    level: 3,
    school: "Abjuration",
    components: "V, S",
    description:
      "Wybierasz do sześciu istot w promieniu 30 stóp: zyskują one przewagę przy rzutach obronnych przed śmiercią i testach na Mądrość, a leczenie przywraca im maksymalną liczbę punktów życia. Trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self (30 ft)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Bestow Curse": {
    name: "Bestow Curse",
    namePl: "Rzucenie klątwy",
    level: 3,
    school: "Necromancy",
    components: "V, S",
    description:
      "Dotykasz istoty, która wykonuje rzut obronny na Mądrość; nieudany oznacza, że zostaje dotknięta klątwą na minutę. Ataki wymierzone w nią wykonuje się z przewagą — DM rozstrzyga dodatkowe efekty wybranego rodzaju klątwy.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Blink": {
    name: "Blink",
    namePl: "Mruganie",
    level: 3,
    school: "Transmutation",
    components: "V, S",
    description:
      "Na końcu twojej tury rzuć k20: przy wyniku 11 lub więcej przenosisz się na Płaszczyznę Eteryczną i wracasz na początku następnej tury w wybranym, widocznym miejscu. Trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Call Lightning": {
    name: "Call Lightning",
    namePl: "Przyzwanie błyskawicy",
    level: 3,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przyzywasz burzowe chmury w promieniu 120 stóp; jako akcję wywołujesz błyskawicę uderzającą w wybrany punkt. Każda istota w walcu o promieniu 5 stóp wykonuje rzut obronny na Zręczność; nieudany oznacza 3k10 obrażeń od błyskawic, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "3d10",
      damageType: "lightning",
      attack: false,
      save: "dexterity",
      range: "Self (120 ft)",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Clairvoyance": {
    name: "Clairvoyance",
    namePl: "Jasnowidzenie",
    level: 3,
    school: "Divination",
    components: "V, S, M",
    description:
      "Tworzysz niewidzialny czujnik w miejscu oddalonym o milę, przez który widzisz lub słyszysz otoczenie (do wyboru przy rzuceniu). Efekt trwa 10 minut i nie wymaga koncentracji.",
    effect: {
      kind: "none",
      range: "1 mile",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Conjure Animals": {
    name: "Conjure Animals",
    namePl: "Przyzwanie zwierząt",
    level: 3,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz duchy bestii w wybrane miejsce w zasięgu 60 stóp; walczą po twojej stronie przez 10 minut, o ile utrzymujesz koncentrację. Liczbę i rodzaj zwierząt (np. stado wilków lub kilka niedźwiedzi) rozstrzyga DM.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Conjure Barrage": {
    name: "Conjure Barrage",
    namePl: "Deszcz broni",
    level: 3,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Rzucasz magiczną broń w stożek o długości 60 stóp; istoty w obszarze wykonują rzut obronny na Zręczność, a nieudany oznacza 5k8 obrażeń siłowych, udany — połowę. Efekt jest natychmiastowy i nie wymaga koncentracji.",
    effect: {
      kind: "none",
      range: "Self (60 ft cone)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Conjure Minor Elementals": {
    name: "Conjure Minor Elementals",
    namePl: "Przyzwanie mniejszych żywiołaków",
    level: 3,
    school: "Conjuration",
    components: "V, S",
    description:
      "Przywołujesz żywiołaki (np. magmowe lub dymne) w wybrane miejsce w zasięgu 90 stóp; walczą po twojej stronie przez 10 minut, o ile utrzymujesz koncentrację. Liczbę i rodzaj żywiołaków rozstrzyga DM.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Counterspell": {
    name: "Counterspell",
    namePl: "Kontrzaklęcie",
    level: 3,
    school: "Abjuration",
    components: "S",
    description:
      "Rzucasz to zaklęcie jako reakcję, gdy widzisz istotę rzucającą zaklęcie w zasięgu 60 stóp (w danych silnika oznaczane jako akcja). Zaklęcie celu nieudaje się — DM rozstrzyga, czy zaklęcie 3. kręgu lub niższe zostaje całkowicie unicestwione.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Create Food and Water": {
    name: "Create Food and Water",
    namePl: "Stworzenie jedzenia i wody",
    level: 3,
    school: "Conjuration",
    components: "V, S",
    description:
      "Tworzysz w zasięgu 30 stóp wystarczająco dużo jedzenia i wody, by wyżywić 15 istot na 24 godziny. Stworzone jedzenie jest mdłe, ale pożywne i nie psuje się do następnego świtu.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Crusader's Mantle": {
    name: "Crusader's Mantle",
    namePl: "Płaszcz krzyżowca",
    level: 3,
    school: "Evocation",
    components: "V",
    description:
      "Święta energia otacza ciebie i sojuszników w promieniu 30 stóp; gdy trafią atakiem bronią, zadają dodatkowo 1k4 obrażeń promienistych. Trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Self (30 ft)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Daylight": {
    name: "Daylight",
    namePl: "Światło dzienne",
    level: 3,
    school: "Evocation",
    components: "V, S",
    description:
      "Tworzysz sferę światła o promieniu 60 stóp w zasięgu 60 stóp; jest to światło dzienne, które rozprasza ciemność z zaklęć niższego kręgu i oślepia istoty wrażliwe na słońce. Trwa godzinę i nie wymaga koncentracji.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Dispel Magic": {
    name: "Dispel Magic",
    namePl: "Rozproszenie magii",
    level: 3,
    school: "Abjuration",
    components: "V, S",
    description:
      "Wybierasz istotę, przedmiot lub obszar w zasięgu 120 stóp i kończysz na nim działanie zaklęcia 3. kręgu lub niższego. Efekty z wyższych kręgów wymagają udanego testu zdolności rzucania zaklęć — DM rozstrzyga wynik.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Elemental Weapon": {
    name: "Elemental Weapon",
    namePl: "Żywiołowa broń",
    level: 3,
    school: "Transmutation",
    components: "V, S",
    description:
      "Dotknięta, niemagiczna broń staje się magiczna, zyskuje premię +1 do ataków i obrażeń oraz zadaje dodatkowe 1k4 obrażeń wybranego typu żywiołowego (kwas, lód, ogień, błyskawica lub grzmot). Efekt trwa godzinę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Erupting Earth": {
    name: "Erupting Earth",
    namePl: "Wybuchająca ziemia",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Ziemia w sześcianie o boku 20 stóp w zasięgu 120 stóp wybucha skałami i gruzem. Każda istota w obszarze wykonuje rzut obronny na Zręczność; nieudany oznacza 3k12 obrażeń obuchowych, udany — połowę, a obszar staje się trudnym terenem.",
    effect: {
      kind: "damage",
      dice: "3d12",
      damageType: "bludgeoning",
      attack: false,
      save: "dexterity",
      range: "120 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Fear": {
    name: "Fear",
    namePl: "Strach",
    level: 3,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Projektujesz widmo grozy w stożku o długości 30 stóp; cele wykonują rzut obronny na Mądrość. Nieudany oznacza stan przerażenia: istoty upuszczają trzymane przedmioty i oddalają się od ciebie, a na końcu swojej tury mogą ponowić rzut obronny.",
    effect: {
      kind: "condition_apply",
      condition: "frightened",
      save: "wisdom",
      range: "Self (30 ft cone)",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Fireball": {
    name: "Fireball",
    namePl: "Kula ognia",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Jasny płomień eksploduje w punkcie w zasięgu 150 stóp, wypełniając sferę o promieniu 20 stóp. Każda istota w obszarze wykonuje rzut obronny na Zręczność; nieudany oznacza 8k6 obrażeń ogniowych, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "8d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Flame Arrows": {
    name: "Flame Arrows",
    namePl: "Ogniste strzały",
    level: 3,
    school: "Transmutation",
    components: "V, S",
    description:
      "Dotykasz do dwunastu sztuk amunicji, które płoną magicznym ogniem: trafione nimi ataki zadają dodatkowe 1k6 obrażeń ogniowych. Efekt trwa godzinę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Fly": {
    name: "Fly",
    namePl: "Lot",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota zyskuje prędkość lotu 60 stóp na 10 minut, o ile utrzymujesz koncentrację. Gdy zaklęcie się kończy, cel opada bezpiecznie na ziemię, jeśli nadal znajduje się w powietrzu.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Gaseous Form": {
    name: "Gaseous Form",
    namePl: "Gazowa forma",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota i jej wyposażenie zamieniają się w obłok mgły: zyskuje odporność na obrażenia od broni, nie może atakować ani rzucać zaklęć, ale przeciska się przez szczeliny. Trwa godzinę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Glyph of Warding": {
    name: "Glyph of Warding",
    namePl: "Glyf ochronny",
    level: 3,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Wpisujesz glyf na powierzchni w zasięgu dotyku — eksplodujący run lub przechowywane zaklęcie. Uaktywnia się, gdy spełniony zostanie wybrany warunek; DM rozstrzyga skutki wybuchu i przechowywanej magii.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Until dispelled or triggered",
      castingTime: "action",
    },
  },
  "Haste": {
    name: "Haste",
    namePl: "Przyśpieszenie",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Dotknięta istota w zasięgu 30 stóp zyskuje premię +2 do Klas Pancerza, przewagę przy rzutach obronnych na Zręczność, podwojoną prędkość i dodatkową akcję w każdej turze. Gdy koncentracja ustanie, cel nie może działać do końca swojej następnej tury.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Hypnotic Pattern": {
    name: "Hypnotic Pattern",
    namePl: "Hipnotyczny wzór",
    level: 3,
    school: "Illusion",
    components: "S, M",
    description:
      "Kuszący wzór barw wiruje w sześcianie o boku 30 stóp w zasięgu 120 stóp; istoty w obszarze wykonują rzut obronny na Mądrość. Nieudany oznacza stan obezwładnienia (z elementem oczarowania) na czas trwania zaklęcia — efekt kończy się po otrzymaniu obrażeń.",
    effect: {
      kind: "condition_apply",
      condition: "incapacitated",
      save: "wisdom",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Leomund's Tiny Hut": {
    name: "Leomund's Tiny Hut",
    namePl: "Namiocik Leomunda",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Półsfera niewidzialnej energii o promieniu 10 stóp otacza ciebie i chroni przed pogodą, pociskami i istotami z zewnątrz. Trwa 8 godzin; zaklęcie można rzucić jako rytuał — idealne na nocny odpoczynek.",
    effect: {
      kind: "none",
      range: "Self (10 ft radius)",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Lightning Bolt": {
    name: "Lightning Bolt",
    namePl: "Piorun",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Piorun przecina linię o długości 100 stóp; każda istota na jej trasie wykonuje rzut obronny na Zręczność. Nieudany oznacza 8k6 obrażeń od błyskawic, udany — połowę.",
    effect: {
      kind: "damage",
      dice: "8d6",
      damageType: "lightning",
      attack: false,
      save: "dexterity",
      range: "Self (100 ft line)",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Magic Circle": {
    name: "Magic Circle",
    namePl: "Magiczny krąg",
    level: 3,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Tworzysz okrąg o promieniu 10 stóp, który oddziela istoty wybranego typu (np. nieumarłych lub smoki): nie mogą one przekroczyć kręgu ani dosięgnąć istot w środku. Trwa godzinę i może również wiązać przywołane istoty.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Major Image": {
    name: "Major Image",
    namePl: "Większa iluzja",
    level: 3,
    school: "Illusion",
    components: "V, S, M",
    description:
      "Tworzysz iluzję dźwięków, obrazów i zapachów w zasięgu 120 stóp, która może się poruszać i wydaje się rzeczywista. Utrzymuje się 10 minut przy koncentracji, a następnie jeszcze 10 minut bez niej — badanie iluzji ujawnia jej fałsz.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Mass Healing Word": {
    name: "Mass Healing Word",
    namePl: "Masowe uzdrawiające słowo",
    level: 3,
    school: "Evocation",
    components: "V",
    description:
      "Wypowiadasz uzdrawiające słowo (akcja dodatkowa): do sześciu istot w zasięgu 60 stóp odzyskuje 1k4 + modyfikator zdolności rzucania zaklęć punktów życia. Idealne do natychmiastowego przywrócenia kilku poległych sojuszników.",
    effect: {
      kind: "heal_all",
      dice: "1d4",
      mod: true,
      range: "60 ft",
      duration: "Instantaneous",
      castingTime: "bonus",
    } as unknown as SpellEffect,
  },
  "Melf's Minute Meteors": {
    name: "Melf's Minute Meteors",
    namePl: "Minutowe meteory Melfa",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Tworzysz sześć maleńkich meteorów krążących wokół ciebie; jako akcję dodatkową wystrzeliwujesz do dwóch z nich w cele w zasięgu 120 stóp. Każdy cel wykonuje rzut obronny na Zręczność; nieudany oznacza 2k6 obrażeń ogniowych.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "fire",
      attack: false,
      save: "dexterity",
      range: "Self (120 ft)",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Nondetection": {
    name: "Nondetection",
    namePl: "Niewykrywalność",
    level: 3,
    school: "Abjuration",
    components: "V, S, M",
    description:
      "Dotknięta istota lub przedmiot staje się niewidzialna dla magii wróżebnej i skryta przed magicznym wykrywaniem na 8 godzin. Zaklęcia wróżebne skierowane w cel nie ujawniają o nim żadnych informacji.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "8 h",
      castingTime: "action",
    },
  },
  "Phantom Steed": {
    name: "Phantom Steed",
    namePl: "Fantasmagoryczny wierzchowiec",
    level: 3,
    school: "Illusion",
    components: "V, S",
    description:
      "Przywołujesz widmowego konia w zasięgu 30 stóp, który znika po otrzymaniu obrażeń; podróżujący nim i do trzech towarzyszy pokonują większe odległości w krótszym czasie. Wierzchowiec trwa godzinę, a zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Plant Growth": {
    name: "Plant Growth",
    namePl: "Wzrost roślin",
    level: 3,
    school: "Transmutation",
    components: "V, S",
    description:
      "Rośliny w promieniu 100 stóp wokół punktu w zasięgu 150 stóp wybujały: obszar staje się trudnym terenem, spowalniającym wrogów. Wariant rzucany przez 8 godzin użyźnia ziemię w promieniu pół mili — DM rozstrzyga efekty gospodarcze.",
    effect: {
      kind: "none",
      range: "150 ft",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Protection from Energy": {
    name: "Protection from Energy",
    namePl: "Ochrona przed energią",
    level: 3,
    school: "Abjuration",
    components: "V, S",
    description:
      "Dotknięta istota zyskuje odporność na jeden wybrany typ obrażeń: kwas, lód, ogień, błyskawicę lub grzmot. Efekt trwa godzinę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Remove Curse": {
    name: "Remove Curse",
    namePl: "Zdjęcie klątwy",
    level: 3,
    school: "Abjuration",
    components: "V, S",
    description:
      "Dotyk przerywa wszystkie klątwy i przekleństwa ciążące na istocie lub przedmiocie, w tym wpływ zaczarowanych przedmiotów. Zaklęcie działa natychmiast i nie wymaga koncentracji.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "Instantaneous",
      castingTime: "action",
    },
  },
  "Sleet Storm": {
    name: "Sleet Storm",
    namePl: "Śnieżna burza",
    level: 3,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Zamieć śniegu i lodu wypełnia walec o promieniu 40 stóp i wysokości 20 stóp w zasięgu 150 stóp, zaciemniając obszar i gasząc pochodnie. Teren w jej obrębie jest trudny, a istoty, które go opuszczą lub w nim wystartują, muszą wykonać rzut obronny na Zręczność, by nie upaść.",
    effect: {
      kind: "none",
      range: "150 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Slow": {
    name: "Slow",
    namePl: "Spowolnienie",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Wybierasz do sześciu istot w zasięgu 120 stóp; każda wykonuje rzut obronny na Mądrość. Nieudany oznacza stan spowolnienia: prędkość spada o połowę, a cel ma utrudnienie przy rzutach obronnych na Zręczność i traci akcję dodatkową (silnik nie modeluje stanu „spowolniony” — efekt rozstrzyga DM).",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Speak with Dead": {
    name: "Speak with Dead",
    namePl: "Rozmowa ze zmarłym",
    level: 3,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Pozwalasz zwłokom w zasięgu 10 stóp odpowiadać na pytania w języku, którym władały za życia — do pięciu pytań w ciągu 10 minut. Zwłoki odpowiadają lakonicznie i mogą kłamać, a ich wiedza kończy się w chwili śmierci.",
    effect: {
      kind: "none",
      range: "10 ft",
      duration: "10 min",
      castingTime: "action",
    },
  },
  "Spirit Shroud": {
    name: "Spirit Shroud",
    namePl: "Płaszcz duchów",
    level: 3,
    school: "Necromancy",
    components: "V, S",
    description:
      "Widmowe światło otula twoje ciało: ataki, którymi trafiasz istotę w promieniu 10 stóp, zadają dodatkowe 1k8 obrażeń promienistych (rzucający może zamiast tego wybrać nekrotyczne lub lodowe). Istoty w promieniu 10 stóp mają też zmniejszoną prędkość.",
    effect: {
      kind: "damage",
      dice: "1d8",
      damageType: "radiant",
      attack: true,
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Stinking Cloud": {
    name: "Stinking Cloud",
    namePl: "Smrodliwa chmura",
    level: 3,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Gęsty, cuchnący gaz wypełnia sferę o promieniu 20 stóp w zasięgu 90 stóp. Istoty wchodzące na ten obszar lub rozpoczynające w nim turę wykonują rzut obronny na Kondycję; nieudany oznacza stan zatrucia i obezwładnienia na czas trwania zaklęcia.",
    effect: {
      kind: "condition_apply",
      condition: "poisoned",
      save: "constitution",
      range: "90 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Summon Fey": {
    name: "Summon Fey",
    namePl: "Przyzwanie fei",
    level: 3,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz ducha fei w wybrane miejsce w zasięgu 90 stóp; walczy po twojej stronie przez godzinę, o ile utrzymujesz koncentrację. Duch przyjmuje wybraną przez ciebie formę (radość lub gniew) — DM rozstrzyga jego statystyki i zdolności.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Summon Shadowspawn": {
    name: "Summon Shadowspawn",
    namePl: "Przyzwanie cienistego sługi",
    level: 3,
    school: "Conjuration",
    components: "V, S, M",
    description:
      "Przywołujesz cienistego ducha w wybrane miejsce w zasięgu 90 stóp; walczy po twojej stronie przez godzinę, o ile utrzymujesz koncentrację. Wybrana forma (gniew, tęsknota lub strach) nadaje mu inne zdolności — DM rozstrzyga szczegóły.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Summon Undead": {
    name: "Summon Undead",
    namePl: "Przyzwanie nieumarłego",
    level: 3,
    school: "Necromancy",
    components: "V, S, M",
    description:
      "Przywołujesz ducha nieumarłego (kościotrupa, widmowego łotrzyka lub zgrozy) w wybrane miejsce w zasięgu 90 stóp; walczy po twojej stronie przez godzinę, o ile utrzymujesz koncentrację. DM rozstrzyga statystyki przywołanej istoty.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "1 h",
      castingTime: "action",
      concentration: true,
    },
  },
  "Tongues": {
    name: "Tongues",
    namePl: "Języki",
    level: 3,
    school: "Divination",
    components: "V, M",
    description:
      "Dotknięta istota rozumie każdy język, jaki słyszy, a jej mowa jest zrozumiała dla wszystkich istot, które ją słyszą, przez godzinę. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "Touch",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Vampiric Touch": {
    name: "Vampiric Touch",
    namePl: "Wampirzy dotyk",
    level: 3,
    school: "Necromancy",
    components: "V, S",
    description:
      "Twoją dłoń spowija ciemna energia: wykonaj rzut ataku zaklęciem w zwarciu, a trafienie zadaje 2k6 obrażeń nekrotycznych i leczy cię o połowę zadanych obrażeń. Efekt trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "damage",
      dice: "2d6",
      damageType: "necrotic",
      attack: true,
      range: "Self",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wall of Sand": {
    name: "Wall of Sand",
    namePl: "Ściana piasku",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Wirująca ściana piasku o długości do 30 stóp, wysokości 10 stóp i grubości 5 stóp wyrasta w zasięgu 90 stóp, zasłaniając widok i utrudniając przejście. Istoty przeciskające się przez ścianę muszą wykonać test Siły — DM rozstrzyga skutki.",
    effect: {
      kind: "none",
      range: "90 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Wall of Water": {
    name: "Wall of Water",
    namePl: "Ściana wody",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Ściana wody o długości do 30 stóp, wysokości 10 stóp i grubości 1 stopy wyrasta w zasięgu 60 stóp. Obrażenia ogniowe przechodzące przez ścianę są zmniejszone o połowę, a ataki dystansowe wykonane przez nią mają utrudnienie.",
    effect: {
      kind: "none",
      range: "60 ft",
      duration: "10 min",
      castingTime: "action",
      concentration: true,
    },
  },
  "Water Breathing": {
    name: "Water Breathing",
    namePl: "Oddychanie pod wodą",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Do dziesięciu istot w zasięgu 30 stóp zyskuje zdolność oddychania pod wodą przez 24 godziny. Zaklęcie można rzucić jako rytuał — niezbędne przy podwodnych wyprawach.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "24 h",
      castingTime: "action",
    },
  },
  "Water Walk": {
    name: "Water Walk",
    namePl: "Chodzenie po wodzie",
    level: 3,
    school: "Transmutation",
    components: "V, S, M",
    description:
      "Do dziesięciu istot w zasięgu 30 stóp zyskuje zdolność chodzenia po powierzchni cieczy, jakby była stałym gruntem, przez godzinę. Zaklęcie można rzucić jako rytuał.",
    effect: {
      kind: "none",
      range: "30 ft",
      duration: "1 h",
      castingTime: "action",
    },
  },
  "Wind Wall": {
    name: "Wind Wall",
    namePl: "Ściana wiatru",
    level: 3,
    school: "Evocation",
    components: "V, S, M",
    description:
      "Ściana silnego wiatru o długości do 50 stóp, wysokości 15 stóp i grubości 1 stopy wyrasta w zasięgu 120 stóp: blokuje strzały i pociski, a istoty przeciskające się przez nią muszą wykonać test Siły. Trwa minutę, o ile utrzymujesz koncentrację.",
    effect: {
      kind: "none",
      range: "120 ft",
      duration: "1 min",
      castingTime: "action",
      concentration: true,
    },
  },
};
