import type { EquipmentSlotInfo, SrdGearItem } from "@domino/shared";

export const EQUIPMENT_SLOTS: EquipmentSlotInfo[] = [
  { key: "head", label: "Głowa" },
  { key: "neck", label: "Szyja" },
  { key: "cloak", label: "Płaszcz" },
  { key: "armor", label: "Zbroja" },
  { key: "gloves", label: "Rękawice" },
  { key: "belt", label: "Pas" },
  { key: "ring", label: "Pierścień" },
  { key: "weapon", label: "Broń" },
  { key: "offhand", label: "Ręka lewa" },
  { key: "shield", label: "Tarcza" },
  { key: "boots", label: "Buty" },
];

function priceInGp(price: string): number {
  if (price === "—") return 500;
  const [amount, unit] = price.split(" ");
  const value = parseFloat(amount ?? "0");
  if (unit === "sp") return value / 10;
  if (unit === "cp") return value / 100;
  return value;
}

export function carryingCapacity(str: number): number {
  return str * 15;
}

export function totalInventoryWeight(
  inventory: { weight?: number; quantity: number }[],
): number {
  return inventory.reduce(
    (sum, item) => sum + (item.weight ?? 0) * item.quantity,
    0,
  );
}

export function isEncumbered(
  str: number,
  inventory: { weight?: number; quantity: number }[],
): boolean {
  return totalInventoryWeight(inventory) > carryingCapacity(str);
}

export function isSlotKey(key: string): boolean {
  return EQUIPMENT_SLOTS.some((s) => s.key === key);
}

export function slotLabel(key: string): string | undefined {
  return EQUIPMENT_SLOTS.find((s) => s.key === key)?.label;
}

export const SRD_GEAR: SrdGearItem[] = [
  {
    name: "Leather",
    icon: "ShieldCheck",
    category: "armor",
    slot: "armor",
    weight: 10,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Lekka zbroja z garbowanej, sztywnej skóry.",
  },
  {
    name: "Studded Leather",
    icon: "ShieldCheck",
    category: "armor",
    slot: "armor",
    weight: 13,
    price: "45 gp",
    priceGp: priceInGp("45 gp"),
    description: "Skórzana zbroja wzmocniona metalowymi ćwiekami.",
  },
  {
    name: "Chain Shirt",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 20,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Koszula z metalowych ogniwek chroniąca tułów.",
  },
  {
    name: "Scale Mail",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 45,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Zbroja z zachodzących na siebie metalowych łusek.",
  },
  {
    name: "Breastplate",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 20,
    price: "400 gp",
    priceGp: priceInGp("400 gp"),
    description: "Napierśnik osłaniający klatkę piersiową i brzuch.",
  },
  {
    name: "Half Plate",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 40,
    price: "750 gp",
    priceGp: priceInGp("750 gp"),
    description: "Zbroja łącząca napierśnik ze stalowymi elementami.",
  },
  {
    name: "Ring Mail",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 40,
    price: "30 gp",
    priceGp: priceInGp("30 gp"),
    description: "Skórzana zbroja naszyta metalowymi pierścieniami.",
  },
  {
    name: "Chain Mail",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 55,
    price: "75 gp",
    priceGp: priceInGp("75 gp"),
    description: "Kolczuga okrywająca całe ciało.",
  },
  {
    name: "Splint",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 60,
    price: "200 gp",
    priceGp: priceInGp("200 gp"),
    description: "Zbroja z metalowych płyt przymocowanych do podkładu.",
  },
  {
    name: "Plate",
    icon: "Shield",
    category: "armor",
    slot: "armor",
    weight: 65,
    price: "1500 gp",
    priceGp: priceInGp("1500 gp"),
    description: "Pełna płyta bojowa zapewniająca najlepszą ochronę.",
  },
  {
    name: "Shield",
    icon: "Shield",
    category: "armor",
    slot: "shield",
    weight: 6,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Tarcza zwiększająca klasę pancerza o 2.",
  },
  {
    name: "Club",
    icon: "Swords",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "2 sp",
    priceGp: priceInGp("2 sp"),
    description: "Prosta, ciężka maczuga.",
  },
  {
    name: "Dagger",
    icon: "Slice",
    category: "weapon",
    slot: "weapon",
    weight: 1,
    price: "2 gp",
    priceGp: priceInGp("2 gp"),
    description: "Krótki sztylet do walki wręcz i rzucania.",
  },
  {
    name: "Handaxe",
    icon: "Axe",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "5 gp",
    priceGp: priceInGp("5 gp"),
    description: "Niewielki topór, którym można także rzucać.",
  },
  {
    name: "Javelin",
    icon: "Crosshair",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "5 sp",
    priceGp: priceInGp("5 sp"),
    description: "Lekki oszczep do walki wręcz i rzucania.",
  },
  {
    name: "Mace",
    icon: "Hammer",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "5 gp",
    priceGp: priceInGp("5 gp"),
    description: "Bulawa z ciężką metalową głowicą.",
  },
  {
    name: "Quarterstaff",
    icon: "Swords",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "2 sp",
    priceGp: priceInGp("2 sp"),
    description: "Długi, prosty kij bojowy.",
  },
  {
    name: "Spear",
    icon: "Swords",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Włócznia z żelaznym grotem, można nią rzucać.",
  },
  {
    name: "Light Crossbow",
    icon: "Crosshair",
    category: "weapon",
    slot: "weapon",
    weight: 5,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Lekka kusza strzelająca bełtami.",
  },
  {
    name: "Shortbow",
    icon: "Crosshair",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Mały, łatwy w obsłudze łuk.",
  },
  {
    name: "Battleaxe",
    icon: "Axe",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Topór bojowy do walki wręcz.",
  },
  {
    name: "Flail",
    icon: "Hammer",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Cep bojowy z łańcuchem i kolczastą głowicą.",
  },
  {
    name: "Glaive",
    icon: "Swords",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "20 gp",
    priceGp: priceInGp("20 gp"),
    description: "Broń drzewcowa z ostrzem osadzonym na długim drzewcu.",
  },
  {
    name: "Greataxe",
    icon: "Axe",
    category: "weapon",
    slot: "weapon",
    weight: 7,
    price: "30 gp",
    priceGp: priceInGp("30 gp"),
    description: "Wielki topór dwuręczny o ogromnej sile ciosu.",
  },
  {
    name: "Greatsword",
    icon: "Sword",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Ogromny, dwuręczny miecz.",
  },
  {
    name: "Halberd",
    icon: "Swords",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "20 gp",
    priceGp: priceInGp("20 gp"),
    description: "Halabarda łącząca ostrze topora i grot.",
  },
  {
    name: "Longsword",
    icon: "Sword",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "15 gp",
    priceGp: priceInGp("15 gp"),
    description: "Klasyczny miecz trzymany w jednej ręce.",
  },
  {
    name: "Maul",
    icon: "Hammer",
    category: "weapon",
    slot: "weapon",
    weight: 10,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Młot bojowy o ogromnej głowicy.",
  },
  {
    name: "Warhammer",
    icon: "Hammer",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "15 gp",
    priceGp: priceInGp("15 gp"),
    description: "Młot bojowy do walki jedną ręką.",
  },
  {
    name: "Rapier",
    icon: "Sword",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Lekka broń kłująca o cienkim, ostrym ostrzu.",
  },
  {
    name: "Scimitar",
    icon: "Sword",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Zakrzywiona, jednosieczna szabla.",
  },
  {
    name: "Shortsword",
    icon: "Sword",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Krótki miecz do walki wręcz.",
  },
  {
    name: "Longbow",
    icon: "Crosshair",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Długi łuk o wielkim zasięgu.",
  },
  {
    name: "Heavy Crossbow",
    icon: "Crosshair",
    category: "weapon",
    slot: "weapon",
    weight: 18,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Ciężka kusza o dużej sile przebicia.",
  },
  {
    name: "Backpack",
    icon: "Backpack",
    category: "gear",
    weight: 5,
    price: "2 gp",
    priceGp: priceInGp("2 gp"),
    description: "Pleciony plecak do przenoszenia ekwipunku.",
  },
  {
    name: "Arrow",
    icon: "Crosshair",
    category: "gear",
    weight: 0.05,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Strzała do krótkiego lub długiego łuku (20 szt. za 1 gp).",
  },
  {
    name: "Holy Symbol",
    icon: "Sparkles",
    category: "gear",
    weight: 1,
    price: "5 gp",
    priceGp: priceInGp("5 gp"),
    description: "Symbol bóstwa używany jako ognisko skupienia zaklęć.",
  },
  {
    name: "Book",
    icon: "BookOpen",
    category: "gear",
    weight: 5,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Księga z modlitwami lub zapiskami historii.",
  },
  {
    name: "Robe",
    icon: "Shirt",
    category: "gear",
    weight: 4,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Prosta szata zakonna lub uczonego.",
  },
  {
    name: "Parchment",
    icon: "ScrollText",
    category: "gear",
    weight: 0.05,
    price: "1 sp",
    priceGp: priceInGp("1 sp"),
    description: "Arkusz pergaminu do zapisków (cena za 10 arkuszy).",
  },
  {
    name: "Calligrapher's Supplies",
    icon: "Pen",
    category: "gear",
    weight: 5,
    price: "10 gp",
    priceGp: priceInGp("10 gp"),
    description: "Przybory kaligraficzne — pióra, atrament i papier.",
  },
  {
    name: "Thieves' Tools",
    icon: "Wrench",
    category: "gear",
    weight: 1,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Wytrychy i narzędzia do otwierania zamków i rozbrajania pułapek.",
  },
  {
    name: "Gaming Set",
    icon: "Dices",
    category: "gear",
    weight: 1,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Zestaw do gry — kości, karty lub plansza.",
  },
  {
    name: "Healer's Kit",
    icon: "Cross",
    category: "gear",
    weight: 3,
    price: "5 gp",
    priceGp: priceInGp("5 gp"),
    description: "Bandaże i zioła — 10 użyć do stabilizacji lub leczenia.",
  },
  {
    name: "Traveler's Clothes",
    icon: "Shirt",
    category: "gear",
    weight: 4,
    price: "2 gp",
    priceGp: priceInGp("2 gp"),
    description: "Odporna odzież podróżna.",
  },
  {
    name: "Quiver",
    icon: "Square",
    category: "gear",
    weight: 1,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Kołczan na strzały.",
  },
  {
    name: "Pouch",
    icon: "Square",
    category: "gear",
    weight: 1,
    price: "5 sp",
    priceGp: priceInGp("5 sp"),
    description: "Skórzany woreczek na drobiazgi.",
  },
  {
    name: "Bedroll",
    icon: "Bed",
    category: "gear",
    weight: 7,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Zwijany posłanie do spania w terenie.",
  },
  {
    name: "Candle",
    icon: "Flame",
    category: "gear",
    price: "1 cp",
    priceGp: priceInGp("1 cp"),
    description: "Woskowa świeca rozpraszająca ciemność.",
  },
  {
    name: "Crowbar",
    icon: "Wrench",
    category: "gear",
    weight: 5,
    price: "2 gp",
    priceGp: priceInGp("2 gp"),
    description: "Łom dający przewagę w testach Siły przy podważaniu.",
  },
  {
    name: "Flint and Steel",
    icon: "Flame",
    category: "gear",
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Krzesiwo służące do rozpalania ognia.",
  },
  {
    name: "Hempen Rope",
    icon: "Link2",
    category: "gear",
    weight: 10,
    price: "1 gp",
    priceGp: priceInGp("1 gp"),
    description: "Wytrzymała lina konopna o długości 50 stóp.",
  },
  {
    name: "Hooded Lantern",
    icon: "Lamp",
    category: "gear",
    weight: 2,
    price: "5 gp",
    priceGp: priceInGp("5 gp"),
    description: "Latarnia z klapką regulującą snop światła.",
  },
  {
    name: "Rations",
    icon: "CookingPot",
    category: "gear",
    weight: 2,
    price: "5 sp",
    priceGp: priceInGp("5 sp"),
    description: "Jednodniowa racja żywnościowa.",
  },
  {
    name: "Torch",
    icon: "Flame",
    category: "gear",
    weight: 1,
    price: "1 cp",
    priceGp: priceInGp("1 cp"),
    description: "Smolna pochodnia świecąca przez 1 godzinę.",
  },
  {
    name: "Waterskin",
    icon: "GlassWater",
    category: "gear",
    weight: 5,
    price: "2 sp",
    priceGp: priceInGp("2 sp"),
    description: "Bukłak mieszczący pół galona wody.",
  },
  {
    name: "Component Pouch",
    icon: "Pocket",
    category: "gear",
    weight: 2,
    price: "25 gp",
    priceGp: priceInGp("25 gp"),
    description: "Sakiewka z drobnymi komponentami do rzucania zaklęć.",
  },
  {
    name: "Spellbook",
    icon: "Book",
    category: "gear",
    weight: 3,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Księga zapisana formułami zaklęć maga.",
  },
  {
    name: "Amulet of Health",
    icon: "Gem",
    category: "magic",
    slot: "neck",
    weight: 3,
    price: "—",
    priceGp: priceInGp("—"),
    description: "Ustawia Kondycję na 19, wymaga atunementu.",
    attuned: true,
  },
  {
    name: "Boots of Elvenkind",
    icon: "Footprints",
    category: "magic",
    slot: "boots",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "Ciche stąpanie — przewaga w Skradaniu się.",
    attuned: true,
  },
  {
    name: "Bracers of Defense",
    icon: "Hand",
    category: "magic",
    slot: "gloves",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "AC +2, gdy nie nosisz zbroi ani tarczy.",
    attuned: true,
  },
  {
    name: "Cloak of Protection",
    icon: "Shirt",
    category: "magic",
    slot: "cloak",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "AC +1 i przewaga w rzutach obronnych.",
    attuned: true,
  },
  {
    name: "Gauntlets of Ogre Power",
    icon: "Hand",
    category: "magic",
    slot: "gloves",
    weight: 2,
    price: "—",
    priceGp: priceInGp("—"),
    description: "Ustawia Siłę na 19.",
    attuned: true,
  },
  {
    name: "Headband of Intellect",
    icon: "Crown",
    category: "magic",
    slot: "head",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "Ustawia Inteligencję na 19.",
    attuned: true,
  },
  {
    name: "Ring of Protection",
    icon: "CircleDot",
    category: "magic",
    slot: "ring",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "AC +1 i przewaga w rzutach obronnych.",
    attuned: true,
  },
  {
    name: "Wand of Magic Missiles",
    icon: "Wand2",
    category: "magic",
    slot: "weapon",
    weight: 1,
    price: "—",
    priceGp: priceInGp("—"),
    description: "7 pocisków, przywraca 1k6+1 na świcie.",
    attuned: true,
  },
  {
    name: "Potion of Healing",
    icon: "FlaskConical",
    category: "magic",
    weight: 0.5,
    price: "50 gp",
    priceGp: priceInGp("50 gp"),
    description: "Mikstura leczenia: akcja — odzyskujesz 2k4+2 punktów życia. Jednorazowa.",
  },
  {
    name: "Greater Potion of Healing",
    icon: "FlaskConical",
    category: "magic",
    weight: 0.5,
    price: "150 gp",
    priceGp: priceInGp("150 gp"),
    description: "Mikstura leczenia: akcja — odzyskujesz 4k4+4 punktów życia. Jednorazowa.",
  },
  {
    name: "Superior Potion of Healing",
    icon: "FlaskConical",
    category: "magic",
    weight: 0.5,
    price: "450 gp",
    priceGp: priceInGp("450 gp"),
    description: "Mikstura leczenia: akcja — odzyskujesz 8k4+8 punktów życia. Jednorazowa.",
  },
  {
    name: "Supreme Potion of Healing",
    icon: "FlaskConical",
    category: "magic",
    weight: 0.5,
    price: "1350 gp",
    priceGp: priceInGp("1350 gp"),
    description: "Mikstura leczenia: akcja — odzyskujesz 10k4+20 punktów życia. Jednorazowa.",
  },
];

export const ATTUNEMENT_LIMIT = 3;
