import type { EquipmentSlotInfo, SrdGearItem } from "@domino/shared";

export const EQUIPMENT_SLOTS: EquipmentSlotInfo[] = [
  { key: "head", label: "Głowa" },
  { key: "neck", label: "Szyja" },
  { key: "cloak", label: "Płaszcz" },
  { key: "armor", label: "Zbroja" },
  { key: "gloves", label: "Rękawice" },
  { key: "belt", label: "Pas" },
  { key: "ring", label: "Pierścień" },
  { key: "weapon", label: "Broń" },
  { key: "shield", label: "Tarcza" },
  { key: "boots", label: "Buty" },
];

export function isSlotKey(key: string): boolean {
  return EQUIPMENT_SLOTS.some((s) => s.key === key);
}

export function slotLabel(key: string): string | undefined {
  return EQUIPMENT_SLOTS.find((s) => s.key === key)?.label;
}

export const SRD_GEAR: SrdGearItem[] = [
  {
    name: "Leather",
    category: "armor",
    slot: "armor",
    weight: 10,
    price: "10 gp",
    description: "Lekka zbroja z garbowanej, sztywnej skóry.",
  },
  {
    name: "Studded Leather",
    category: "armor",
    slot: "armor",
    weight: 13,
    price: "45 gp",
    description: "Skórzana zbroja wzmocniona metalowymi ćwiekami.",
  },
  {
    name: "Chain Shirt",
    category: "armor",
    slot: "armor",
    weight: 20,
    price: "50 gp",
    description: "Koszula z metalowych ogniwek chroniąca tułów.",
  },
  {
    name: "Scale Mail",
    category: "armor",
    slot: "armor",
    weight: 45,
    price: "50 gp",
    description: "Zbroja z zachodzących na siebie metalowych łusek.",
  },
  {
    name: "Breastplate",
    category: "armor",
    slot: "armor",
    weight: 20,
    price: "400 gp",
    description: "Napierśnik osłaniający klatkę piersiową i brzuch.",
  },
  {
    name: "Half Plate",
    category: "armor",
    slot: "armor",
    weight: 40,
    price: "750 gp",
    description: "Zbroja łącząca napierśnik ze stalowymi elementami.",
  },
  {
    name: "Ring Mail",
    category: "armor",
    slot: "armor",
    weight: 40,
    price: "30 gp",
    description: "Skórzana zbroja naszyta metalowymi pierścieniami.",
  },
  {
    name: "Chain Mail",
    category: "armor",
    slot: "armor",
    weight: 55,
    price: "75 gp",
    description: "Kolczuga okrywająca całe ciało.",
  },
  {
    name: "Splint",
    category: "armor",
    slot: "armor",
    weight: 60,
    price: "200 gp",
    description: "Zbroja z metalowych płyt przymocowanych do podkładu.",
  },
  {
    name: "Plate",
    category: "armor",
    slot: "armor",
    weight: 65,
    price: "1500 gp",
    description: "Pełna płyta bojowa zapewniająca najlepszą ochronę.",
  },
  {
    name: "Shield",
    category: "armor",
    slot: "shield",
    weight: 6,
    price: "10 gp",
    description: "Tarcza zwiększająca klasę pancerza o 2.",
  },
  {
    name: "Club",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "2 sp",
    description: "Prosta, ciężka maczuga.",
  },
  {
    name: "Dagger",
    category: "weapon",
    slot: "weapon",
    weight: 1,
    price: "2 gp",
    description: "Krótki sztylet do walki wręcz i rzucania.",
  },
  {
    name: "Handaxe",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "5 gp",
    description: "Niewielki topór, którym można także rzucać.",
  },
  {
    name: "Javelin",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "5 sp",
    description: "Lekki oszczep do walki wręcz i rzucania.",
  },
  {
    name: "Mace",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "5 gp",
    description: "Bulawa z ciężką metalową głowicą.",
  },
  {
    name: "Quarterstaff",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "2 sp",
    description: "Długi, prosty kij bojowy.",
  },
  {
    name: "Spear",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "1 gp",
    description: "Włócznia z żelaznym grotem, można nią rzucać.",
  },
  {
    name: "Light Crossbow",
    category: "weapon",
    slot: "weapon",
    weight: 5,
    price: "25 gp",
    description: "Lekka kusza strzelająca bełtami.",
  },
  {
    name: "Shortbow",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "25 gp",
    description: "Mały, łatwy w obsłudze łuk.",
  },
  {
    name: "Battleaxe",
    category: "weapon",
    slot: "weapon",
    weight: 4,
    price: "10 gp",
    description: "Topór bojowy do walki wręcz.",
  },
  {
    name: "Flail",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "10 gp",
    description: "Cep bojowy z łańcuchem i kolczastą głowicą.",
  },
  {
    name: "Glaive",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "20 gp",
    description: "Broń drzewcowa z ostrzem osadzonym na długim drzewcu.",
  },
  {
    name: "Greataxe",
    category: "weapon",
    slot: "weapon",
    weight: 7,
    price: "30 gp",
    description: "Wielki topór dwuręczny o ogromnej sile ciosu.",
  },
  {
    name: "Greatsword",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "50 gp",
    description: "Ogromny, dwuręczny miecz.",
  },
  {
    name: "Halberd",
    category: "weapon",
    slot: "weapon",
    weight: 6,
    price: "20 gp",
    description: "Halabarda łącząca ostrze topora i grot.",
  },
  {
    name: "Longsword",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "15 gp",
    description: "Klasyczny miecz trzymany w jednej ręce.",
  },
  {
    name: "Maul",
    category: "weapon",
    slot: "weapon",
    weight: 10,
    price: "10 gp",
    description: "Młot bojowy o ogromnej głowicy.",
  },
  {
    name: "Warhammer",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "15 gp",
    description: "Młot bojowy do walki jedną ręką.",
  },
  {
    name: "Rapier",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "25 gp",
    description: "Lekka broń kłująca o cienkim, ostrym ostrzu.",
  },
  {
    name: "Scimitar",
    category: "weapon",
    slot: "weapon",
    weight: 3,
    price: "25 gp",
    description: "Zakrzywiona, jednosieczna szabla.",
  },
  {
    name: "Shortsword",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "10 gp",
    description: "Krótki miecz do walki wręcz.",
  },
  {
    name: "Longbow",
    category: "weapon",
    slot: "weapon",
    weight: 2,
    price: "50 gp",
    description: "Długi łuk o wielkim zasięgu.",
  },
  {
    name: "Heavy Crossbow",
    category: "weapon",
    slot: "weapon",
    weight: 18,
    price: "50 gp",
    description: "Ciężka kusza o dużej sile przebicia.",
  },
  {
    name: "Backpack",
    category: "gear",
    weight: 5,
    price: "2 gp",
    description: "Pleciony plecak do przenoszenia ekwipunku.",
  },
  {
    name: "Bedroll",
    category: "gear",
    weight: 7,
    price: "1 gp",
    description: "Zwijany posłanie do spania w terenie.",
  },
  {
    name: "Candle",
    category: "gear",
    price: "1 cp",
    description: "Woskowa świeca rozpraszająca ciemność.",
  },
  {
    name: "Crowbar",
    category: "gear",
    weight: 5,
    price: "2 gp",
    description: "Łom dający przewagę w testach Siły przy podważaniu.",
  },
  {
    name: "Flint and Steel",
    category: "gear",
    price: "1 gp",
    description: "Krzesiwo służące do rozpalania ognia.",
  },
  {
    name: "Hempen Rope",
    category: "gear",
    weight: 10,
    price: "1 gp",
    description: "Wytrzymała lina konopna o długości 50 stóp.",
  },
  {
    name: "Hooded Lantern",
    category: "gear",
    weight: 2,
    price: "5 gp",
    description: "Latarnia z klapką regulującą snop światła.",
  },
  {
    name: "Rations",
    category: "gear",
    weight: 2,
    price: "5 sp",
    description: "Jednodniowa racja żywnościowa.",
  },
  {
    name: "Torch",
    category: "gear",
    weight: 1,
    price: "1 cp",
    description: "Smolna pochodnia świecąca przez 1 godzinę.",
  },
  {
    name: "Waterskin",
    category: "gear",
    weight: 5,
    price: "2 sp",
    description: "Bukłak mieszczący pół galona wody.",
  },
  {
    name: "Component Pouch",
    category: "gear",
    weight: 2,
    price: "25 gp",
    description: "Sakiewka z drobnymi komponentami do rzucania zaklęć.",
  },
  {
    name: "Spellbook",
    category: "gear",
    weight: 3,
    price: "50 gp",
    description: "Księga zapisana formułami zaklęć maga.",
  },
  {
    name: "Amulet of Health",
    category: "magic",
    slot: "neck",
    weight: 3,
    price: "—",
    description: "Ustawia Kondycję na 19, wymaga atunementu.",
    attuned: true,
  },
  {
    name: "Boots of Elvenkind",
    category: "magic",
    slot: "boots",
    weight: 1,
    price: "—",
    description: "Ciche stąpanie — przewaga w Skradaniu się.",
    attuned: true,
  },
  {
    name: "Bracers of Defense",
    category: "magic",
    slot: "gloves",
    weight: 1,
    price: "—",
    description: "AC +2, gdy nie nosisz zbroi ani tarczy.",
    attuned: true,
  },
  {
    name: "Cloak of Protection",
    category: "magic",
    slot: "cloak",
    weight: 1,
    price: "—",
    description: "AC +1 i przewaga w rzutach obronnych.",
    attuned: true,
  },
  {
    name: "Gauntlets of Ogre Power",
    category: "magic",
    slot: "gloves",
    weight: 2,
    price: "—",
    description: "Ustawia Siłę na 19.",
    attuned: true,
  },
  {
    name: "Headband of Intellect",
    category: "magic",
    slot: "head",
    weight: 1,
    price: "—",
    description: "Ustawia Inteligencję na 19.",
    attuned: true,
  },
  {
    name: "Ring of Protection",
    category: "magic",
    slot: "ring",
    weight: 1,
    price: "—",
    description: "AC +1 i przewaga w rzutach obronnych.",
    attuned: true,
  },
  {
    name: "Wand of Magic Missiles",
    category: "magic",
    slot: "weapon",
    weight: 1,
    price: "—",
    description: "7 pocisków, przywraca 1k6+1 na świcie.",
    attuned: true,
  },
];

export const ATTUNEMENT_LIMIT = 3;
